// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_hw_stream_sobel_hw_stream,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=65685,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1358,HLS_SYN_LUT=2990,HLS_VERSION=2020_2}" *)

module sobel_hw_stream (
        ap_clk,
        ap_rst_n,
        in_pix_TDATA,
        in_pix_TVALID,
        in_pix_TREADY,
        in_pix_TKEEP,
        in_pix_TSTRB,
        in_pix_TLAST,
        out_pix_TDATA,
        out_pix_TVALID,
        out_pix_TREADY,
        out_pix_TKEEP,
        out_pix_TSTRB,
        out_pix_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp1_stage0 = 5'd8;
parameter    ap_ST_fsm_state23 = 5'd16;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] in_pix_TDATA;
input   in_pix_TVALID;
output   in_pix_TREADY;
input  [0:0] in_pix_TKEEP;
input  [0:0] in_pix_TSTRB;
input  [0:0] in_pix_TLAST;
output  [7:0] out_pix_TDATA;
output   out_pix_TVALID;
input   out_pix_TREADY;
output  [0:0] out_pix_TKEEP;
output  [0:0] out_pix_TSTRB;
output  [0:0] out_pix_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [0:0] init_done;
reg   [7:0] line1_V_address0;
reg    line1_V_ce0;
reg    line1_V_we0;
reg   [7:0] line1_V_d0;
wire   [7:0] line1_V_q0;
reg   [7:0] line2_V_address0;
reg    line2_V_ce0;
reg    line2_V_we0;
reg   [7:0] line2_V_d0;
wire   [7:0] line2_V_address1;
reg    line2_V_ce1;
wire   [7:0] line2_V_q1;
reg    in_pix_TDATA_blk_n;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire   [0:0] icmp_ln38_fu_369_p2;
reg    out_pix_TDATA_blk_n;
reg    ap_enable_reg_pp1_iter17;
reg   [0:0] icmp_ln38_reg_896;
reg   [0:0] icmp_ln38_reg_896_pp1_iter16_reg;
reg    ap_enable_reg_pp1_iter18;
reg   [0:0] icmp_ln38_reg_896_pp1_iter17_reg;
reg   [16:0] indvar_flatten_reg_220;
reg   [8:0] x_reg_231;
reg   [7:0] w21_V_reg_242;
reg   [7:0] w01_V_1_reg_254;
reg   [7:0] w01_V_reg_265;
reg   [7:0] w11_V_1_reg_278;
reg   [7:0] w11_V_reg_289;
reg   [7:0] w21_V_2_reg_302;
reg   [8:0] y_reg_314;
wire   [0:0] init_done_load_load_fu_335_p1;
reg   [0:0] init_done_load_reg_879;
wire   [8:0] add_ln26_fu_339_p2;
wire    ap_CS_fsm_state2;
wire   [16:0] add_ln38_fu_363_p2;
reg    ap_block_state4_pp1_stage0_iter0;
wire    ap_block_state5_pp1_stage0_iter1;
wire    ap_block_state6_pp1_stage0_iter2;
wire    ap_block_state7_pp1_stage0_iter3;
wire    ap_block_state8_pp1_stage0_iter4;
wire    ap_block_state9_pp1_stage0_iter5;
wire    ap_block_state10_pp1_stage0_iter6;
wire    ap_block_state11_pp1_stage0_iter7;
wire    ap_block_state12_pp1_stage0_iter8;
wire    ap_block_state13_pp1_stage0_iter9;
wire    ap_block_state14_pp1_stage0_iter10;
wire    ap_block_state15_pp1_stage0_iter11;
wire    ap_block_state16_pp1_stage0_iter12;
wire    ap_block_state17_pp1_stage0_iter13;
wire    ap_block_state18_pp1_stage0_iter14;
wire    ap_block_state19_pp1_stage0_iter15;
wire    ap_block_state20_pp1_stage0_iter16;
reg    ap_block_state21_pp1_stage0_iter17;
reg    ap_block_state21_io;
reg    ap_block_state22_pp1_stage0_iter18;
reg    ap_block_state22_io;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] icmp_ln38_reg_896_pp1_iter1_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter2_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter3_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter4_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter5_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter6_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter7_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter8_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter9_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter10_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter11_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter12_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter13_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter14_reg;
reg   [0:0] icmp_ln38_reg_896_pp1_iter15_reg;
wire   [0:0] icmp_ln39_fu_375_p2;
reg   [0:0] icmp_ln39_reg_900;
reg   [0:0] icmp_ln39_reg_900_pp1_iter1_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter2_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter3_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter4_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter5_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter6_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter7_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter8_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter9_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter10_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter11_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter12_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter13_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter14_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter15_reg;
reg   [0:0] icmp_ln39_reg_900_pp1_iter16_reg;
reg   [7:0] w22_V_reg_907;
reg   [7:0] w22_V_reg_907_pp1_iter1_reg;
reg   [7:0] line2_V_addr_1_reg_919;
wire   [0:0] icmp_ln60_fu_410_p2;
reg   [0:0] icmp_ln60_reg_925;
reg   [0:0] icmp_ln60_reg_925_pp1_iter1_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter2_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter3_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter4_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter5_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter6_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter7_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter8_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter9_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter10_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter11_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter12_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter13_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter14_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter15_reg;
reg   [0:0] icmp_ln60_reg_925_pp1_iter16_reg;
wire   [0:0] icmp_ln84_fu_416_p2;
reg   [0:0] icmp_ln84_reg_930;
reg   [0:0] icmp_ln84_reg_930_pp1_iter1_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter2_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter3_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter4_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter5_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter6_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter7_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter8_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter9_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter10_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter11_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter12_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter13_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter14_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter15_reg;
reg   [0:0] icmp_ln84_reg_930_pp1_iter16_reg;
wire   [8:0] add_ln39_fu_422_p2;
reg   [7:0] w12_V_reg_940;
reg    ap_enable_reg_pp1_iter1;
reg   [7:0] w02_V_reg_946;
wire   [8:0] zext_ln64_1_fu_448_p1;
reg   [8:0] zext_ln64_1_reg_953;
wire   [9:0] add_ln63_fu_462_p2;
reg   [9:0] add_ln63_reg_958;
wire   [10:0] sub_ln67_1_fu_502_p2;
reg   [10:0] sub_ln67_1_reg_963;
wire   [10:0] gx_fu_550_p2;
reg   [10:0] gx_reg_968;
wire   [10:0] gy_fu_570_p2;
reg   [10:0] gy_reg_973;
wire   [62:0] trunc_ln368_fu_588_p1;
reg   [62:0] trunc_ln368_reg_988;
wire   [62:0] trunc_ln368_1_fu_596_p1;
reg   [62:0] trunc_ln368_1_reg_993;
wire   [63:0] grp_fu_325_p2;
reg   [63:0] dc_2_reg_1008;
reg   [0:0] p_Result_2_reg_1013;
wire   [31:0] val_fu_741_p3;
reg   [31:0] val_reg_1018;
wire   [8:0] select_ln38_fu_813_p3;
wire    ap_CS_fsm_state3;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter6;
reg    ap_enable_reg_pp1_iter7;
reg    ap_enable_reg_pp1_iter8;
reg    ap_enable_reg_pp1_iter9;
reg    ap_enable_reg_pp1_iter10;
reg    ap_enable_reg_pp1_iter11;
reg    ap_enable_reg_pp1_iter12;
reg    ap_enable_reg_pp1_iter13;
reg    ap_enable_reg_pp1_iter14;
reg    ap_enable_reg_pp1_iter15;
reg    ap_enable_reg_pp1_iter16;
reg    ap_condition_pp1_exit_iter17_state21;
reg   [8:0] i_reg_209;
wire   [0:0] icmp_ln26_fu_345_p2;
reg   [7:0] ap_phi_mux_w21_V_phi_fu_246_p4;
reg   [7:0] ap_phi_mux_w01_V_1_phi_fu_258_p4;
reg   [7:0] ap_phi_mux_w01_V_phi_fu_270_p4;
reg   [7:0] ap_phi_mux_w11_V_1_phi_fu_282_p4;
reg   [7:0] ap_phi_mux_w21_V_2_phi_fu_306_p4;
wire   [63:0] zext_ln26_fu_351_p1;
wire   [63:0] zext_ln39_fu_389_p1;
reg    ap_block_pp1_stage0_01001;
wire   [63:0] grp_fu_325_p0;
wire   [63:0] grp_fu_325_p1;
wire  signed [31:0] grp_fu_329_p0;
wire  signed [31:0] grp_fu_332_p0;
wire   [8:0] select_ln36_fu_381_p3;
wire   [7:0] tmp_2_fu_400_p4;
wire   [8:0] shl_ln_fu_436_p3;
wire   [8:0] zext_ln62_1_fu_432_p1;
wire   [8:0] add_ln63_1_fu_452_p2;
wire   [9:0] zext_ln63_5_fu_458_p1;
wire   [9:0] zext_ln63_2_fu_444_p1;
wire   [8:0] shl_ln1_fu_468_p3;
wire   [8:0] shl_ln2_fu_480_p3;
wire   [9:0] zext_ln67_fu_488_p1;
wire   [9:0] zext_ln62_fu_428_p1;
wire   [9:0] sub_ln67_fu_492_p2;
wire  signed [10:0] sext_ln67_fu_498_p1;
wire   [10:0] zext_ln68_fu_476_p1;
wire   [8:0] shl_ln63_1_fu_514_p3;
wire   [10:0] zext_ln63_4_fu_528_p1;
wire   [10:0] zext_ln63_6_fu_531_p1;
wire   [9:0] zext_ln64_fu_521_p1;
wire   [9:0] zext_ln63_1_fu_511_p1;
wire   [9:0] add_ln64_fu_540_p2;
wire   [10:0] zext_ln64_2_fu_546_p1;
wire   [10:0] sub_ln63_fu_534_p2;
wire   [8:0] zext_ln63_3_fu_525_p1;
wire   [8:0] add_ln68_fu_556_p2;
wire   [10:0] zext_ln68_1_fu_561_p1;
wire   [10:0] add_ln68_1_fu_565_p2;
wire   [10:0] zext_ln63_fu_508_p1;
wire   [63:0] grp_fu_329_p1;
wire   [63:0] data_V_fu_584_p1;
wire   [63:0] grp_fu_332_p1;
wire   [63:0] data_V_1_fu_592_p1;
wire   [63:0] p_Result_s_fu_600_p3;
wire   [63:0] p_Result_1_fu_612_p3;
wire   [63:0] data_V_2_fu_624_p1;
wire   [51:0] tmp_12_fu_645_p1;
wire   [53:0] mantissa_fu_649_p4;
wire   [10:0] tmp_11_fu_635_p4;
wire   [11:0] zext_ln510_fu_663_p1;
wire   [11:0] add_ln510_fu_667_p2;
wire   [10:0] sub_ln1311_fu_681_p2;
wire   [0:0] isNeg_fu_673_p3;
wire  signed [11:0] sext_ln1311_fu_687_p1;
wire   [11:0] ush_fu_691_p3;
wire  signed [31:0] sh_prom_i_i_i_i_i_cast_cast_cast_fu_699_p1;
wire   [136:0] zext_ln15_fu_659_p1;
wire   [136:0] sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1;
wire   [136:0] r_V_fu_707_p2;
wire   [0:0] tmp_9_fu_719_p3;
wire   [136:0] r_V_1_fu_713_p2;
wire   [31:0] zext_ln662_fu_727_p1;
wire   [31:0] tmp_6_fu_731_p4;
wire   [8:0] add_ln38_1_fu_749_p2;
wire   [7:0] tmp_fu_755_p4;
wire   [7:0] tmp_1_fu_771_p4;
wire   [0:0] icmp_fu_765_p2;
wire   [0:0] icmp13_fu_781_p2;
wire   [0:0] cmp68_mid1_fu_794_p2;
wire   [0:0] cmp685_fu_800_p2;
wire   [0:0] select_ln36_1_fu_787_p3;
wire   [31:0] result_V_2_fu_825_p2;
wire   [31:0] result_V_fu_830_p3;
wire   [23:0] tmp_10_fu_836_p4;
wire   [0:0] icmp_ln71_fu_846_p2;
wire   [7:0] trunc_ln301_fu_852_p1;
wire   [0:0] and_ln60_fu_820_p2;
wire   [7:0] outval_V_fu_856_p3;
wire   [0:0] select_ln36_2_fu_806_p3;
reg    grp_fu_325_ce;
reg    grp_fu_329_ce;
reg    grp_fu_332_ce;
wire    ap_CS_fsm_state23;
wire    regslice_both_out_pix_V_data_V_U_apdone_blk;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    regslice_both_in_pix_V_data_V_U_apdone_blk;
wire   [7:0] in_pix_TDATA_int_regslice;
wire    in_pix_TVALID_int_regslice;
reg    in_pix_TREADY_int_regslice;
wire    regslice_both_in_pix_V_data_V_U_ack_in;
wire    regslice_both_in_pix_V_keep_V_U_apdone_blk;
wire   [0:0] in_pix_TKEEP_int_regslice;
wire    regslice_both_in_pix_V_keep_V_U_vld_out;
wire    regslice_both_in_pix_V_keep_V_U_ack_in;
wire    regslice_both_in_pix_V_strb_V_U_apdone_blk;
wire   [0:0] in_pix_TSTRB_int_regslice;
wire    regslice_both_in_pix_V_strb_V_U_vld_out;
wire    regslice_both_in_pix_V_strb_V_U_ack_in;
wire    regslice_both_in_pix_V_last_V_U_apdone_blk;
wire   [0:0] in_pix_TLAST_int_regslice;
wire    regslice_both_in_pix_V_last_V_U_vld_out;
wire    regslice_both_in_pix_V_last_V_U_ack_in;
wire   [7:0] out_pix_TDATA_int_regslice;
reg    out_pix_TVALID_int_regslice;
wire    out_pix_TREADY_int_regslice;
wire    regslice_both_out_pix_V_data_V_U_vld_out;
wire    regslice_both_out_pix_V_keep_V_U_apdone_blk;
wire    regslice_both_out_pix_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_keep_V_U_vld_out;
wire    regslice_both_out_pix_V_strb_V_U_apdone_blk;
wire    regslice_both_out_pix_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_strb_V_U_vld_out;
wire    regslice_both_out_pix_V_last_V_U_apdone_blk;
wire   [0:0] out_pix_TLAST_int_regslice;
wire    regslice_both_out_pix_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 init_done = 1'd0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter17 = 1'b0;
#0 ap_enable_reg_pp1_iter18 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter11 = 1'b0;
#0 ap_enable_reg_pp1_iter12 = 1'b0;
#0 ap_enable_reg_pp1_iter13 = 1'b0;
#0 ap_enable_reg_pp1_iter14 = 1'b0;
#0 ap_enable_reg_pp1_iter15 = 1'b0;
#0 ap_enable_reg_pp1_iter16 = 1'b0;
end

sobel_hw_stream_line1_V #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line1_V_address0),
    .ce0(line1_V_ce0),
    .we0(line1_V_we0),
    .d0(line1_V_d0),
    .q0(line1_V_q0)
);

sobel_hw_stream_line2_V #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line2_V_address0),
    .ce0(line2_V_ce0),
    .we0(line2_V_we0),
    .d0(line2_V_d0),
    .address1(line2_V_address1),
    .ce1(line2_V_ce1),
    .q1(line2_V_q1)
);

sobel_hw_stream_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

sobel_hw_stream_dadd_64ns_64ns_64_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_7_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_325_p0),
    .din1(grp_fu_325_p1),
    .ce(grp_fu_325_ce),
    .dout(grp_fu_325_p2)
);

sobel_hw_stream_sitodp_32s_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_6_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_329_p0),
    .ce(grp_fu_329_ce),
    .dout(grp_fu_329_p1)
);

sobel_hw_stream_sitodp_32s_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_6_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_332_p0),
    .ce(grp_fu_332_ce),
    .dout(grp_fu_332_p1)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_pix_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TDATA),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_data_V_U_ack_in),
    .data_out(in_pix_TDATA_int_regslice),
    .vld_out(in_pix_TVALID_int_regslice),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_data_V_U_apdone_blk)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_pix_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TKEEP),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_keep_V_U_ack_in),
    .data_out(in_pix_TKEEP_int_regslice),
    .vld_out(regslice_both_in_pix_V_keep_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_keep_V_U_apdone_blk)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_pix_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TSTRB),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_strb_V_U_ack_in),
    .data_out(in_pix_TSTRB_int_regslice),
    .vld_out(regslice_both_in_pix_V_strb_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_strb_V_U_apdone_blk)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_pix_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TLAST),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_last_V_U_ack_in),
    .data_out(in_pix_TLAST_int_regslice),
    .vld_out(regslice_both_in_pix_V_last_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_last_V_U_apdone_blk)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_pix_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pix_TDATA_int_regslice),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(out_pix_TREADY_int_regslice),
    .data_out(out_pix_TDATA),
    .vld_out(regslice_both_out_pix_V_data_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_data_V_U_apdone_blk)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_pix_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_keep_V_U_ack_in_dummy),
    .data_out(out_pix_TKEEP),
    .vld_out(regslice_both_out_pix_V_keep_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_keep_V_U_apdone_blk)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_pix_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_strb_V_U_ack_in_dummy),
    .data_out(out_pix_TSTRB),
    .vld_out(regslice_both_out_pix_V_strb_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_strb_V_U_apdone_blk)
);

sobel_hw_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_pix_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pix_TLAST_int_regslice),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_last_V_U_ack_in_dummy),
    .data_out(out_pix_TLAST),
    .vld_out(regslice_both_out_pix_V_last_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter11 <= ap_enable_reg_pp1_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter12 <= ap_enable_reg_pp1_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter13 <= ap_enable_reg_pp1_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter14 <= ap_enable_reg_pp1_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter15 <= ap_enable_reg_pp1_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter16 <= ap_enable_reg_pp1_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter17 <= ap_enable_reg_pp1_iter16;
        end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter16 == 1'b0) & (1'b1 == ap_condition_pp1_exit_iter17_state21)))) begin
            ap_enable_reg_pp1_iter17 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter18 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter17_state21))) begin
            ap_enable_reg_pp1_iter18 <= ap_enable_reg_pp1_iter16;
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter18 <= ap_enable_reg_pp1_iter17;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter18 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (init_done_load_load_fu_335_p1 == 1'd0) & (ap_start == 1'b1))) begin
        i_reg_209 <= 9'd0;
    end else if (((icmp_ln26_fu_345_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_209 <= add_ln26_fu_339_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        indvar_flatten_reg_220 <= add_ln38_fu_363_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        indvar_flatten_reg_220 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        w01_V_1_reg_254 <= w01_V_reg_265;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        w01_V_1_reg_254 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        w01_V_reg_265 <= w02_V_reg_946;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        w01_V_reg_265 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        w11_V_1_reg_278 <= w11_V_reg_289;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        w11_V_1_reg_278 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        w11_V_reg_289 <= w12_V_reg_940;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        w11_V_reg_289 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        w21_V_2_reg_302 <= w21_V_reg_242;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        w21_V_2_reg_302 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        w21_V_reg_242 <= w22_V_reg_907_pp1_iter1_reg;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        w21_V_reg_242 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        x_reg_231 <= add_ln39_fu_422_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_reg_231 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_reg_896_pp1_iter16_reg == 1'd0) & (ap_enable_reg_pp1_iter17 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        y_reg_314 <= select_ln38_fu_813_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y_reg_314 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_reg_896 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        add_ln63_reg_958 <= add_ln63_fu_462_p2;
        sub_ln67_1_reg_963 <= sub_ln67_1_fu_502_p2;
        zext_ln64_1_reg_953[7 : 0] <= zext_ln64_1_fu_448_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln38_reg_896_pp1_iter14_reg == 1'd0))) begin
        dc_2_reg_1008 <= grp_fu_325_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        gx_reg_968 <= gx_fu_550_p2;
        gy_reg_973 <= gy_fu_570_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln38_reg_896 <= icmp_ln38_fu_369_p2;
        icmp_ln38_reg_896_pp1_iter1_reg <= icmp_ln38_reg_896;
        icmp_ln39_reg_900_pp1_iter1_reg <= icmp_ln39_reg_900;
        icmp_ln60_reg_925_pp1_iter1_reg <= icmp_ln60_reg_925;
        icmp_ln84_reg_930_pp1_iter1_reg <= icmp_ln84_reg_930;
        w22_V_reg_907_pp1_iter1_reg <= w22_V_reg_907;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln38_reg_896_pp1_iter10_reg <= icmp_ln38_reg_896_pp1_iter9_reg;
        icmp_ln38_reg_896_pp1_iter11_reg <= icmp_ln38_reg_896_pp1_iter10_reg;
        icmp_ln38_reg_896_pp1_iter12_reg <= icmp_ln38_reg_896_pp1_iter11_reg;
        icmp_ln38_reg_896_pp1_iter13_reg <= icmp_ln38_reg_896_pp1_iter12_reg;
        icmp_ln38_reg_896_pp1_iter14_reg <= icmp_ln38_reg_896_pp1_iter13_reg;
        icmp_ln38_reg_896_pp1_iter15_reg <= icmp_ln38_reg_896_pp1_iter14_reg;
        icmp_ln38_reg_896_pp1_iter16_reg <= icmp_ln38_reg_896_pp1_iter15_reg;
        icmp_ln38_reg_896_pp1_iter17_reg <= icmp_ln38_reg_896_pp1_iter16_reg;
        icmp_ln38_reg_896_pp1_iter2_reg <= icmp_ln38_reg_896_pp1_iter1_reg;
        icmp_ln38_reg_896_pp1_iter3_reg <= icmp_ln38_reg_896_pp1_iter2_reg;
        icmp_ln38_reg_896_pp1_iter4_reg <= icmp_ln38_reg_896_pp1_iter3_reg;
        icmp_ln38_reg_896_pp1_iter5_reg <= icmp_ln38_reg_896_pp1_iter4_reg;
        icmp_ln38_reg_896_pp1_iter6_reg <= icmp_ln38_reg_896_pp1_iter5_reg;
        icmp_ln38_reg_896_pp1_iter7_reg <= icmp_ln38_reg_896_pp1_iter6_reg;
        icmp_ln38_reg_896_pp1_iter8_reg <= icmp_ln38_reg_896_pp1_iter7_reg;
        icmp_ln38_reg_896_pp1_iter9_reg <= icmp_ln38_reg_896_pp1_iter8_reg;
        icmp_ln39_reg_900_pp1_iter10_reg <= icmp_ln39_reg_900_pp1_iter9_reg;
        icmp_ln39_reg_900_pp1_iter11_reg <= icmp_ln39_reg_900_pp1_iter10_reg;
        icmp_ln39_reg_900_pp1_iter12_reg <= icmp_ln39_reg_900_pp1_iter11_reg;
        icmp_ln39_reg_900_pp1_iter13_reg <= icmp_ln39_reg_900_pp1_iter12_reg;
        icmp_ln39_reg_900_pp1_iter14_reg <= icmp_ln39_reg_900_pp1_iter13_reg;
        icmp_ln39_reg_900_pp1_iter15_reg <= icmp_ln39_reg_900_pp1_iter14_reg;
        icmp_ln39_reg_900_pp1_iter16_reg <= icmp_ln39_reg_900_pp1_iter15_reg;
        icmp_ln39_reg_900_pp1_iter2_reg <= icmp_ln39_reg_900_pp1_iter1_reg;
        icmp_ln39_reg_900_pp1_iter3_reg <= icmp_ln39_reg_900_pp1_iter2_reg;
        icmp_ln39_reg_900_pp1_iter4_reg <= icmp_ln39_reg_900_pp1_iter3_reg;
        icmp_ln39_reg_900_pp1_iter5_reg <= icmp_ln39_reg_900_pp1_iter4_reg;
        icmp_ln39_reg_900_pp1_iter6_reg <= icmp_ln39_reg_900_pp1_iter5_reg;
        icmp_ln39_reg_900_pp1_iter7_reg <= icmp_ln39_reg_900_pp1_iter6_reg;
        icmp_ln39_reg_900_pp1_iter8_reg <= icmp_ln39_reg_900_pp1_iter7_reg;
        icmp_ln39_reg_900_pp1_iter9_reg <= icmp_ln39_reg_900_pp1_iter8_reg;
        icmp_ln60_reg_925_pp1_iter10_reg <= icmp_ln60_reg_925_pp1_iter9_reg;
        icmp_ln60_reg_925_pp1_iter11_reg <= icmp_ln60_reg_925_pp1_iter10_reg;
        icmp_ln60_reg_925_pp1_iter12_reg <= icmp_ln60_reg_925_pp1_iter11_reg;
        icmp_ln60_reg_925_pp1_iter13_reg <= icmp_ln60_reg_925_pp1_iter12_reg;
        icmp_ln60_reg_925_pp1_iter14_reg <= icmp_ln60_reg_925_pp1_iter13_reg;
        icmp_ln60_reg_925_pp1_iter15_reg <= icmp_ln60_reg_925_pp1_iter14_reg;
        icmp_ln60_reg_925_pp1_iter16_reg <= icmp_ln60_reg_925_pp1_iter15_reg;
        icmp_ln60_reg_925_pp1_iter2_reg <= icmp_ln60_reg_925_pp1_iter1_reg;
        icmp_ln60_reg_925_pp1_iter3_reg <= icmp_ln60_reg_925_pp1_iter2_reg;
        icmp_ln60_reg_925_pp1_iter4_reg <= icmp_ln60_reg_925_pp1_iter3_reg;
        icmp_ln60_reg_925_pp1_iter5_reg <= icmp_ln60_reg_925_pp1_iter4_reg;
        icmp_ln60_reg_925_pp1_iter6_reg <= icmp_ln60_reg_925_pp1_iter5_reg;
        icmp_ln60_reg_925_pp1_iter7_reg <= icmp_ln60_reg_925_pp1_iter6_reg;
        icmp_ln60_reg_925_pp1_iter8_reg <= icmp_ln60_reg_925_pp1_iter7_reg;
        icmp_ln60_reg_925_pp1_iter9_reg <= icmp_ln60_reg_925_pp1_iter8_reg;
        icmp_ln84_reg_930_pp1_iter10_reg <= icmp_ln84_reg_930_pp1_iter9_reg;
        icmp_ln84_reg_930_pp1_iter11_reg <= icmp_ln84_reg_930_pp1_iter10_reg;
        icmp_ln84_reg_930_pp1_iter12_reg <= icmp_ln84_reg_930_pp1_iter11_reg;
        icmp_ln84_reg_930_pp1_iter13_reg <= icmp_ln84_reg_930_pp1_iter12_reg;
        icmp_ln84_reg_930_pp1_iter14_reg <= icmp_ln84_reg_930_pp1_iter13_reg;
        icmp_ln84_reg_930_pp1_iter15_reg <= icmp_ln84_reg_930_pp1_iter14_reg;
        icmp_ln84_reg_930_pp1_iter16_reg <= icmp_ln84_reg_930_pp1_iter15_reg;
        icmp_ln84_reg_930_pp1_iter2_reg <= icmp_ln84_reg_930_pp1_iter1_reg;
        icmp_ln84_reg_930_pp1_iter3_reg <= icmp_ln84_reg_930_pp1_iter2_reg;
        icmp_ln84_reg_930_pp1_iter4_reg <= icmp_ln84_reg_930_pp1_iter3_reg;
        icmp_ln84_reg_930_pp1_iter5_reg <= icmp_ln84_reg_930_pp1_iter4_reg;
        icmp_ln84_reg_930_pp1_iter6_reg <= icmp_ln84_reg_930_pp1_iter5_reg;
        icmp_ln84_reg_930_pp1_iter7_reg <= icmp_ln84_reg_930_pp1_iter6_reg;
        icmp_ln84_reg_930_pp1_iter8_reg <= icmp_ln84_reg_930_pp1_iter7_reg;
        icmp_ln84_reg_930_pp1_iter9_reg <= icmp_ln84_reg_930_pp1_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln39_reg_900 <= icmp_ln39_fu_375_p2;
        icmp_ln60_reg_925 <= icmp_ln60_fu_410_p2;
        icmp_ln84_reg_930 <= icmp_ln84_fu_416_p2;
        line2_V_addr_1_reg_919 <= zext_ln39_fu_389_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (init_done_load_reg_879 == 1'd0))) begin
        init_done <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        init_done_load_reg_879 <= init_done;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln38_reg_896_pp1_iter15_reg == 1'd0))) begin
        p_Result_2_reg_1013 <= data_V_2_fu_624_p1[32'd63];
        val_reg_1018 <= val_fu_741_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln38_reg_896_pp1_iter7_reg == 1'd0))) begin
        trunc_ln368_1_reg_993 <= trunc_ln368_1_fu_596_p1;
        trunc_ln368_reg_988 <= trunc_ln368_fu_588_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_reg_896 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        w02_V_reg_946 <= line2_V_q1;
        w12_V_reg_940 <= line1_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        w22_V_reg_907 <= in_pix_TDATA_int_regslice;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter17 == 1'b1) & (ap_enable_reg_pp1_iter16 == 1'b0))) begin
        ap_condition_pp1_exit_iter17_state21 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter17_state21 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_369_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_pix_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state23))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter18 == 1'b0) & (ap_enable_reg_pp1_iter17 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter16 == 1'b0) & (ap_enable_reg_pp1_iter15 == 1'b0) & (ap_enable_reg_pp1_iter14 == 1'b0) & (ap_enable_reg_pp1_iter13 == 1'b0) & (ap_enable_reg_pp1_iter12 == 1'b0) & (ap_enable_reg_pp1_iter11 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        ap_phi_mux_w01_V_1_phi_fu_258_p4 = w01_V_reg_265;
    end else begin
        ap_phi_mux_w01_V_1_phi_fu_258_p4 = w01_V_1_reg_254;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        ap_phi_mux_w01_V_phi_fu_270_p4 = w02_V_reg_946;
    end else begin
        ap_phi_mux_w01_V_phi_fu_270_p4 = w01_V_reg_265;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        ap_phi_mux_w11_V_1_phi_fu_282_p4 = w11_V_reg_289;
    end else begin
        ap_phi_mux_w11_V_1_phi_fu_282_p4 = w11_V_1_reg_278;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        ap_phi_mux_w21_V_2_phi_fu_306_p4 = w21_V_reg_242;
    end else begin
        ap_phi_mux_w21_V_2_phi_fu_306_p4 = w21_V_2_reg_302;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln38_reg_896_pp1_iter1_reg == 1'd0))) begin
        ap_phi_mux_w21_V_phi_fu_246_p4 = w22_V_reg_907_pp1_iter1_reg;
    end else begin
        ap_phi_mux_w21_V_phi_fu_246_p4 = w21_V_reg_242;
    end
end

always @ (*) begin
    if (((regslice_both_out_pix_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state23))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_325_ce = 1'b1;
    end else begin
        grp_fu_325_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_329_ce = 1'b1;
    end else begin
        grp_fu_329_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_332_ce = 1'b1;
    end else begin
        grp_fu_332_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        in_pix_TDATA_blk_n = in_pix_TVALID_int_regslice;
    end else begin
        in_pix_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        in_pix_TREADY_int_regslice = 1'b1;
    end else begin
        in_pix_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line1_V_address0 = zext_ln39_fu_389_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line1_V_address0 = zext_ln26_fu_351_p1;
    end else begin
        line1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        line1_V_ce0 = 1'b1;
    end else begin
        line1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line1_V_d0 = in_pix_TDATA_int_regslice;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line1_V_d0 = 8'd0;
    end else begin
        line1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln38_fu_369_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((icmp_ln26_fu_345_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        line1_V_we0 = 1'b1;
    end else begin
        line1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line2_V_address0 = line2_V_addr_1_reg_919;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line2_V_address0 = zext_ln26_fu_351_p1;
    end else begin
        line2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        line2_V_ce0 = 1'b1;
    end else begin
        line2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line2_V_ce1 = 1'b1;
    end else begin
        line2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line2_V_d0 = line1_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line2_V_d0 = 8'd0;
    end else begin
        line2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln26_fu_345_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln38_reg_896 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        line2_V_we0 = 1'b1;
    end else begin
        line2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln38_reg_896_pp1_iter17_reg == 1'd0) & (ap_enable_reg_pp1_iter18 == 1'b1) & (1'b0 == ap_block_pp1_stage0)) | ((icmp_ln38_reg_896_pp1_iter16_reg == 1'd0) & (ap_enable_reg_pp1_iter17 == 1'b1) & (1'b0 == ap_block_pp1_stage0)))) begin
        out_pix_TDATA_blk_n = out_pix_TREADY_int_regslice;
    end else begin
        out_pix_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln38_reg_896_pp1_iter16_reg == 1'd0) & (ap_enable_reg_pp1_iter17 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        out_pix_TVALID_int_regslice = 1'b1;
    end else begin
        out_pix_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (init_done_load_load_fu_335_p1 == 1'd0) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (init_done_load_load_fu_335_p1 == 1'd1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln26_fu_345_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_enable_reg_pp1_iter17 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter16 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter17 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter16 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((regslice_both_out_pix_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln26_fu_339_p2 = (i_reg_209 + 9'd1);

assign add_ln38_1_fu_749_p2 = (y_reg_314 + 9'd1);

assign add_ln38_fu_363_p2 = (indvar_flatten_reg_220 + 17'd1);

assign add_ln39_fu_422_p2 = (select_ln36_fu_381_p3 + 9'd1);

assign add_ln510_fu_667_p2 = ($signed(zext_ln510_fu_663_p1) + $signed(12'd3073));

assign add_ln63_1_fu_452_p2 = (zext_ln62_1_fu_432_p1 + zext_ln64_1_fu_448_p1);

assign add_ln63_fu_462_p2 = (zext_ln63_5_fu_458_p1 + zext_ln63_2_fu_444_p1);

assign add_ln64_fu_540_p2 = (zext_ln64_fu_521_p1 + zext_ln63_1_fu_511_p1);

assign add_ln68_1_fu_565_p2 = (zext_ln68_1_fu_561_p1 + sub_ln67_1_reg_963);

assign add_ln68_fu_556_p2 = (zext_ln64_1_reg_953 + zext_ln63_3_fu_525_p1);

assign and_ln60_fu_820_p2 = (select_ln36_1_fu_787_p3 & icmp_ln60_reg_925_pp1_iter16_reg);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter17_reg == 1'd0) & (ap_enable_reg_pp1_iter18 == 1'b1)) | ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter16_reg == 1'd0) & (ap_enable_reg_pp1_iter17 == 1'b1)) | ((in_pix_TVALID_int_regslice == 1'b0) & (icmp_ln38_fu_369_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((in_pix_TVALID_int_regslice == 1'b0) & (icmp_ln38_fu_369_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter18 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter17_reg == 1'd0)))) | ((ap_enable_reg_pp1_iter17 == 1'b1) & ((1'b1 == ap_block_state21_io) | ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter16_reg == 1'd0)))));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((in_pix_TVALID_int_regslice == 1'b0) & (icmp_ln38_fu_369_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter18 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter17_reg == 1'd0)))) | ((ap_enable_reg_pp1_iter17 == 1'b1) & ((1'b1 == ap_block_state21_io) | ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter16_reg == 1'd0)))));
end

assign ap_block_state10_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp1_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp1_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp1_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp1_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage0_iter16 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_io = ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter16_reg == 1'd0));
end

always @ (*) begin
    ap_block_state21_pp1_stage0_iter17 = ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter16_reg == 1'd0));
end

always @ (*) begin
    ap_block_state22_io = ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter17_reg == 1'd0));
end

always @ (*) begin
    ap_block_state22_pp1_stage0_iter18 = ((out_pix_TREADY_int_regslice == 1'b0) & (icmp_ln38_reg_896_pp1_iter17_reg == 1'd0));
end

always @ (*) begin
    ap_block_state4_pp1_stage0_iter0 = ((in_pix_TVALID_int_regslice == 1'b0) & (icmp_ln38_fu_369_p2 == 1'd0));
end

assign ap_block_state5_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp685_fu_800_p2 = ((y_reg_314 == 9'd255) ? 1'b1 : 1'b0);

assign cmp68_mid1_fu_794_p2 = ((add_ln38_1_fu_749_p2 == 9'd255) ? 1'b1 : 1'b0);

assign data_V_1_fu_592_p1 = grp_fu_332_p1;

assign data_V_2_fu_624_p1 = dc_2_reg_1008;

assign data_V_fu_584_p1 = grp_fu_329_p1;

assign grp_fu_325_p0 = p_Result_s_fu_600_p3;

assign grp_fu_325_p1 = p_Result_1_fu_612_p3;

assign grp_fu_329_p0 = $signed(gx_reg_968);

assign grp_fu_332_p0 = $signed(gy_reg_973);

assign gx_fu_550_p2 = (zext_ln64_2_fu_546_p1 + sub_ln63_fu_534_p2);

assign gy_fu_570_p2 = (add_ln68_1_fu_565_p2 - zext_ln63_fu_508_p1);

assign icmp13_fu_781_p2 = ((tmp_1_fu_771_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_fu_765_p2 = ((tmp_fu_755_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_345_p2 = ((i_reg_209 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_369_p2 = ((indvar_flatten_reg_220 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_375_p2 = ((x_reg_231 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_410_p2 = ((tmp_2_fu_400_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_846_p2 = (($signed(tmp_10_fu_836_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_416_p2 = ((select_ln36_fu_381_p3 == 9'd255) ? 1'b1 : 1'b0);

assign in_pix_TREADY = regslice_both_in_pix_V_data_V_U_ack_in;

assign init_done_load_load_fu_335_p1 = init_done;

assign isNeg_fu_673_p3 = add_ln510_fu_667_p2[32'd11];

assign line2_V_address1 = zext_ln39_fu_389_p1;

assign mantissa_fu_649_p4 = {{{{1'd1}, {tmp_12_fu_645_p1}}}, {1'd0}};

assign out_pix_TDATA_int_regslice = ((and_ln60_fu_820_p2[0:0] == 1'b1) ? outval_V_fu_856_p3 : 8'd0);

assign out_pix_TLAST_int_regslice = (select_ln36_2_fu_806_p3 & icmp_ln84_reg_930_pp1_iter16_reg);

assign out_pix_TVALID = regslice_both_out_pix_V_data_V_U_vld_out;

assign outval_V_fu_856_p3 = ((icmp_ln71_fu_846_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln301_fu_852_p1);

assign p_Result_1_fu_612_p3 = {{1'd0}, {trunc_ln368_1_reg_993}};

assign p_Result_s_fu_600_p3 = {{1'd0}, {trunc_ln368_reg_988}};

assign r_V_1_fu_713_p2 = zext_ln15_fu_659_p1 << sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1;

assign r_V_fu_707_p2 = zext_ln15_fu_659_p1 >> sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1;

assign result_V_2_fu_825_p2 = (32'd0 - val_reg_1018);

assign result_V_fu_830_p3 = ((p_Result_2_reg_1013[0:0] == 1'b1) ? result_V_2_fu_825_p2 : val_reg_1018);

assign select_ln36_1_fu_787_p3 = ((icmp_ln39_reg_900_pp1_iter16_reg[0:0] == 1'b1) ? icmp_fu_765_p2 : icmp13_fu_781_p2);

assign select_ln36_2_fu_806_p3 = ((icmp_ln39_reg_900_pp1_iter16_reg[0:0] == 1'b1) ? cmp68_mid1_fu_794_p2 : cmp685_fu_800_p2);

assign select_ln36_fu_381_p3 = ((icmp_ln39_fu_375_p2[0:0] == 1'b1) ? 9'd0 : x_reg_231);

assign select_ln38_fu_813_p3 = ((icmp_ln39_reg_900_pp1_iter16_reg[0:0] == 1'b1) ? add_ln38_1_fu_749_p2 : y_reg_314);

assign sext_ln1311_fu_687_p1 = $signed(sub_ln1311_fu_681_p2);

assign sext_ln67_fu_498_p1 = $signed(sub_ln67_fu_492_p2);

assign sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1 = $unsigned(sh_prom_i_i_i_i_i_cast_cast_cast_fu_699_p1);

assign sh_prom_i_i_i_i_i_cast_cast_cast_fu_699_p1 = $signed(ush_fu_691_p3);

assign shl_ln1_fu_468_p3 = {{ap_phi_mux_w01_V_phi_fu_270_p4}, {1'd0}};

assign shl_ln2_fu_480_p3 = {{ap_phi_mux_w21_V_phi_fu_246_p4}, {1'd0}};

assign shl_ln63_1_fu_514_p3 = {{w12_V_reg_940}, {1'd0}};

assign shl_ln_fu_436_p3 = {{ap_phi_mux_w11_V_1_phi_fu_282_p4}, {1'd0}};

assign sub_ln1311_fu_681_p2 = (11'd1023 - tmp_11_fu_635_p4);

assign sub_ln63_fu_534_p2 = (zext_ln63_4_fu_528_p1 - zext_ln63_6_fu_531_p1);

assign sub_ln67_1_fu_502_p2 = ($signed(sext_ln67_fu_498_p1) - $signed(zext_ln68_fu_476_p1));

assign sub_ln67_fu_492_p2 = (zext_ln67_fu_488_p1 - zext_ln62_fu_428_p1);

assign tmp_10_fu_836_p4 = {{result_V_fu_830_p3[31:8]}};

assign tmp_11_fu_635_p4 = {{data_V_2_fu_624_p1[62:52]}};

assign tmp_12_fu_645_p1 = data_V_2_fu_624_p1[51:0];

assign tmp_1_fu_771_p4 = {{y_reg_314[8:1]}};

assign tmp_2_fu_400_p4 = {{select_ln36_fu_381_p3[8:1]}};

assign tmp_6_fu_731_p4 = {{r_V_1_fu_713_p2[84:53]}};

assign tmp_9_fu_719_p3 = r_V_fu_707_p2[32'd53];

assign tmp_fu_755_p4 = {{add_ln38_1_fu_749_p2[8:1]}};

assign trunc_ln301_fu_852_p1 = result_V_fu_830_p3[7:0];

assign trunc_ln368_1_fu_596_p1 = data_V_1_fu_592_p1[62:0];

assign trunc_ln368_fu_588_p1 = data_V_fu_584_p1[62:0];

assign ush_fu_691_p3 = ((isNeg_fu_673_p3[0:0] == 1'b1) ? sext_ln1311_fu_687_p1 : add_ln510_fu_667_p2);

assign val_fu_741_p3 = ((isNeg_fu_673_p3[0:0] == 1'b1) ? zext_ln662_fu_727_p1 : tmp_6_fu_731_p4);

assign zext_ln15_fu_659_p1 = mantissa_fu_649_p4;

assign zext_ln26_fu_351_p1 = i_reg_209;

assign zext_ln39_fu_389_p1 = select_ln36_fu_381_p3;

assign zext_ln510_fu_663_p1 = tmp_11_fu_635_p4;

assign zext_ln62_1_fu_432_p1 = ap_phi_mux_w01_V_1_phi_fu_258_p4;

assign zext_ln62_fu_428_p1 = ap_phi_mux_w01_V_1_phi_fu_258_p4;

assign zext_ln63_1_fu_511_p1 = w02_V_reg_946;

assign zext_ln63_2_fu_444_p1 = shl_ln_fu_436_p3;

assign zext_ln63_3_fu_525_p1 = w22_V_reg_907_pp1_iter1_reg;

assign zext_ln63_4_fu_528_p1 = w22_V_reg_907_pp1_iter1_reg;

assign zext_ln63_5_fu_458_p1 = add_ln63_1_fu_452_p2;

assign zext_ln63_6_fu_531_p1 = add_ln63_reg_958;

assign zext_ln63_fu_508_p1 = w02_V_reg_946;

assign zext_ln64_1_fu_448_p1 = ap_phi_mux_w21_V_2_phi_fu_306_p4;

assign zext_ln64_2_fu_546_p1 = add_ln64_fu_540_p2;

assign zext_ln64_fu_521_p1 = shl_ln63_1_fu_514_p3;

assign zext_ln662_fu_727_p1 = tmp_9_fu_719_p3;

assign zext_ln67_fu_488_p1 = shl_ln2_fu_480_p3;

assign zext_ln68_1_fu_561_p1 = add_ln68_fu_556_p2;

assign zext_ln68_fu_476_p1 = shl_ln1_fu_468_p3;

always @ (posedge ap_clk) begin
    zext_ln64_1_reg_953[8] <= 1'b0;
end

endmodule //sobel_hw_stream
