// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_video_stream_sobel_video_stream,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=307864,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1597,HLS_SYN_LUT=3100,HLS_VERSION=2020_2}" *)

module sobel_video_stream (
        ap_clk,
        ap_rst_n,
        in_pix_TDATA,
        in_pix_TVALID,
        in_pix_TREADY,
        in_pix_TKEEP,
        in_pix_TSTRB,
        in_pix_TUSER,
        in_pix_TLAST,
        in_pix_TID,
        in_pix_TDEST,
        out_pix_TDATA,
        out_pix_TVALID,
        out_pix_TREADY,
        out_pix_TKEEP,
        out_pix_TSTRB,
        out_pix_TUSER,
        out_pix_TLAST,
        out_pix_TID,
        out_pix_TDEST
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp1_stage0 = 5'd8;
parameter    ap_ST_fsm_state26 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [23:0] in_pix_TDATA;
input   in_pix_TVALID;
output   in_pix_TREADY;
input  [2:0] in_pix_TKEEP;
input  [2:0] in_pix_TSTRB;
input  [0:0] in_pix_TUSER;
input  [0:0] in_pix_TLAST;
input  [0:0] in_pix_TID;
input  [0:0] in_pix_TDEST;
output  [23:0] out_pix_TDATA;
output   out_pix_TVALID;
input   out_pix_TREADY;
output  [2:0] out_pix_TKEEP;
output  [2:0] out_pix_TSTRB;
output  [0:0] out_pix_TUSER;
output  [0:0] out_pix_TLAST;
output  [0:0] out_pix_TID;
output  [0:0] out_pix_TDEST;

 reg    ap_rst_n_inv;
wire   [9:0] line1_V_address0;
reg    line1_V_ce0;
wire   [7:0] line1_V_q0;
reg   [9:0] line1_V_address1;
reg    line1_V_ce1;
reg    line1_V_we1;
reg   [7:0] line1_V_d1;
reg   [9:0] line2_V_address1;
reg    line2_V_ce1;
reg    line2_V_we1;
reg   [7:0] line2_V_d1;
wire   [7:0] line2_V_q1;
reg    in_pix_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire   [0:0] icmp_ln49_fu_423_p2;
reg    out_pix_TDATA_blk_n;
reg    ap_enable_reg_pp1_iter20;
reg   [0:0] icmp_ln49_reg_1022;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter19_reg;
reg    ap_enable_reg_pp1_iter21;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter20_reg;
reg   [18:0] indvar_flatten_reg_284;
reg   [9:0] x_reg_295;
reg   [7:0] w21_V_reg_306;
reg   [7:0] w21_V_2_reg_318;
reg   [7:0] w01_V_1_reg_330;
reg   [7:0] w01_V_reg_341;
reg   [7:0] w11_V_1_reg_354;
reg   [7:0] w11_V_reg_365;
reg   [8:0] y_reg_378;
wire   [9:0] add_ln39_fu_399_p2;
wire    ap_CS_fsm_state2;
wire   [18:0] add_ln49_fu_417_p2;
reg    ap_block_state4_pp1_stage0_iter0;
wire    ap_block_state5_pp1_stage0_iter1;
wire    ap_block_state6_pp1_stage0_iter2;
wire    ap_block_state7_pp1_stage0_iter3;
wire    ap_block_state8_pp1_stage0_iter4;
wire    ap_block_state9_pp1_stage0_iter5;
wire    ap_block_state10_pp1_stage0_iter6;
wire    ap_block_state11_pp1_stage0_iter7;
wire    ap_block_state12_pp1_stage0_iter8;
wire    ap_block_state13_pp1_stage0_iter9;
wire    ap_block_state14_pp1_stage0_iter10;
wire    ap_block_state15_pp1_stage0_iter11;
wire    ap_block_state16_pp1_stage0_iter12;
wire    ap_block_state17_pp1_stage0_iter13;
wire    ap_block_state18_pp1_stage0_iter14;
wire    ap_block_state19_pp1_stage0_iter15;
wire    ap_block_state20_pp1_stage0_iter16;
wire    ap_block_state21_pp1_stage0_iter17;
wire    ap_block_state22_pp1_stage0_iter18;
wire    ap_block_state23_pp1_stage0_iter19;
reg    ap_block_state24_pp1_stage0_iter20;
reg    ap_block_state24_io;
reg    ap_block_state25_pp1_stage0_iter21;
reg    ap_block_state25_io;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter1_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter2_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter3_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter4_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter5_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter6_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter7_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter8_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter9_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter10_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter11_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter12_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter13_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter14_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter15_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter16_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter17_reg;
reg   [0:0] icmp_ln49_reg_1022_pp1_iter18_reg;
wire   [0:0] icmp_ln50_fu_429_p2;
reg   [0:0] icmp_ln50_reg_1026;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter1_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter2_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter3_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter4_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter5_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter6_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter7_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter8_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter9_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter10_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter11_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter12_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter13_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter14_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter15_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter16_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter17_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter18_reg;
reg   [0:0] icmp_ln50_reg_1026_pp1_iter19_reg;
reg   [7:0] g_reg_1033;
wire   [8:0] add_ln208_fu_485_p2;
reg   [8:0] add_ln208_reg_1038;
reg   [9:0] line1_V_addr_1_reg_1043;
reg   [9:0] line1_V_addr_1_reg_1043_pp1_iter1_reg;
reg   [9:0] line1_V_addr_1_reg_1043_pp1_iter2_reg;
reg   [9:0] line1_V_addr_1_reg_1043_pp1_iter3_reg;
reg   [9:0] line2_V_addr_1_reg_1049;
wire   [0:0] icmp_ln70_fu_501_p2;
reg   [0:0] icmp_ln70_reg_1054;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter1_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter2_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter3_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter4_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter5_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter6_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter7_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter8_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter9_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter10_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter11_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter12_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter13_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter14_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter15_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter16_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter17_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter18_reg;
reg   [0:0] icmp_ln70_reg_1054_pp1_iter19_reg;
wire   [0:0] icmp_ln95_fu_507_p2;
reg   [0:0] icmp_ln95_reg_1059;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter1_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter2_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter3_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter4_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter5_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter6_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter7_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter8_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter9_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter10_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter11_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter12_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter13_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter14_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter15_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter16_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter17_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter18_reg;
reg   [0:0] icmp_ln95_reg_1059_pp1_iter19_reg;
wire   [0:0] out_pkt_last_V_fu_513_p2;
reg   [0:0] out_pkt_last_V_reg_1064;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter1_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter2_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter3_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter4_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter5_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter6_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter7_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter8_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter9_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter10_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter11_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter12_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter13_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter14_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter15_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter16_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter17_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter18_reg;
reg   [0:0] out_pkt_last_V_reg_1064_pp1_iter19_reg;
wire   [9:0] add_ln50_fu_519_p2;
reg   [7:0] w12_V_reg_1074;
reg    ap_enable_reg_pp1_iter1;
reg   [7:0] w12_V_reg_1074_pp1_iter2_reg;
reg   [7:0] w12_V_reg_1074_pp1_iter3_reg;
reg   [7:0] w12_V_reg_1074_pp1_iter4_reg;
reg   [7:0] w02_V_reg_1080;
reg    ap_enable_reg_pp1_iter2;
reg   [7:0] w02_V_reg_1080_pp1_iter3_reg;
reg   [7:0] w02_V_reg_1080_pp1_iter4_reg;
reg   [7:0] w22_V_reg_1087;
reg    ap_enable_reg_pp1_iter4;
wire   [9:0] add_ln73_fu_579_p2;
reg   [9:0] add_ln73_reg_1093;
wire   [10:0] sub_ln78_fu_625_p2;
reg   [10:0] sub_ln78_reg_1098;
wire   [10:0] gx_fu_670_p2;
reg   [10:0] gx_reg_1103;
wire   [10:0] gy_fu_681_p2;
reg   [10:0] gy_reg_1108;
wire   [62:0] trunc_ln368_fu_699_p1;
reg   [62:0] trunc_ln368_reg_1123;
wire   [62:0] trunc_ln368_1_fu_707_p1;
reg   [62:0] trunc_ln368_1_reg_1128;
wire   [63:0] grp_fu_389_p2;
reg   [63:0] dc_2_reg_1143;
reg   [0:0] p_Result_2_reg_1148;
wire   [31:0] val_fu_852_p3;
reg   [31:0] val_reg_1153;
wire   [8:0] select_ln49_fu_924_p3;
wire    ap_CS_fsm_state3;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter6;
reg    ap_enable_reg_pp1_iter7;
reg    ap_enable_reg_pp1_iter8;
reg    ap_enable_reg_pp1_iter9;
reg    ap_enable_reg_pp1_iter10;
reg    ap_enable_reg_pp1_iter11;
reg    ap_enable_reg_pp1_iter12;
reg    ap_enable_reg_pp1_iter13;
reg    ap_enable_reg_pp1_iter14;
reg    ap_enable_reg_pp1_iter15;
reg    ap_enable_reg_pp1_iter16;
reg    ap_enable_reg_pp1_iter17;
reg    ap_enable_reg_pp1_iter18;
reg    ap_enable_reg_pp1_iter19;
reg    ap_condition_pp1_exit_iter20_state24;
reg   [9:0] i_reg_273;
wire   [0:0] icmp_ln39_fu_405_p2;
wire    ap_CS_fsm_state1;
reg   [7:0] ap_phi_mux_w21_V_phi_fu_310_p4;
reg   [7:0] ap_phi_mux_w21_V_2_phi_fu_322_p4;
reg   [7:0] ap_phi_mux_w01_V_1_phi_fu_334_p4;
reg   [7:0] ap_phi_mux_w01_V_phi_fu_346_p4;
reg   [7:0] ap_phi_mux_w11_V_1_phi_fu_358_p4;
wire   [63:0] zext_ln39_fu_411_p1;
wire   [63:0] zext_ln50_fu_443_p1;
reg    ap_block_pp1_stage0_01001;
wire   [63:0] grp_fu_389_p0;
wire   [63:0] grp_fu_389_p1;
wire  signed [31:0] grp_fu_393_p0;
wire  signed [31:0] grp_fu_396_p0;
wire   [9:0] select_ln46_fu_435_p3;
wire   [7:0] r_fu_453_p4;
wire   [7:0] b_fu_473_p1;
wire   [8:0] zext_ln208_fu_477_p1;
wire   [8:0] zext_ln208_2_fu_481_p1;
wire   [8:0] tmp_2_fu_491_p4;
wire   [20:0] grp_fu_1000_p3;
wire   [8:0] shl_ln_fu_549_p3;
wire   [8:0] zext_ln72_1_fu_545_p1;
wire   [8:0] zext_ln74_2_fu_565_p1;
wire   [8:0] add_ln73_1_fu_569_p2;
wire   [9:0] zext_ln73_4_fu_575_p1;
wire   [9:0] zext_ln73_2_fu_557_p1;
wire   [8:0] shl_ln1_fu_585_p3;
wire   [8:0] shl_ln2_fu_597_p3;
wire   [9:0] zext_ln77_fu_605_p1;
wire   [9:0] zext_ln74_1_fu_561_p1;
wire   [9:0] add_ln77_fu_609_p2;
wire   [10:0] zext_ln77_1_fu_615_p1;
wire   [10:0] zext_ln72_fu_541_p1;
wire   [10:0] sub_ln77_fu_619_p2;
wire   [10:0] zext_ln78_fu_593_p1;
wire   [8:0] shl_ln73_1_fu_637_p3;
wire   [10:0] zext_ln73_3_fu_648_p1;
wire   [10:0] zext_ln73_5_fu_651_p1;
wire   [9:0] zext_ln74_fu_644_p1;
wire   [9:0] zext_ln73_1_fu_634_p1;
wire   [9:0] add_ln74_fu_660_p2;
wire   [10:0] zext_ln74_3_fu_666_p1;
wire   [10:0] sub_ln73_fu_654_p2;
wire   [10:0] add_ln78_fu_676_p2;
wire   [10:0] zext_ln73_fu_631_p1;
wire   [63:0] grp_fu_393_p1;
wire   [63:0] data_V_fu_695_p1;
wire   [63:0] grp_fu_396_p1;
wire   [63:0] data_V_1_fu_703_p1;
wire   [63:0] p_Result_s_fu_711_p3;
wire   [63:0] p_Result_1_fu_723_p3;
wire   [63:0] data_V_2_fu_735_p1;
wire   [51:0] tmp_12_fu_756_p1;
wire   [53:0] mantissa_fu_760_p4;
wire   [10:0] tmp_11_fu_746_p4;
wire   [11:0] zext_ln510_fu_774_p1;
wire   [11:0] add_ln510_fu_778_p2;
wire   [10:0] sub_ln1311_fu_792_p2;
wire   [0:0] isNeg_fu_784_p3;
wire  signed [11:0] sext_ln1311_fu_798_p1;
wire   [11:0] ush_fu_802_p3;
wire  signed [31:0] sh_prom_i_i_i_i_i_cast_cast_cast_fu_810_p1;
wire   [136:0] zext_ln15_fu_770_p1;
wire   [136:0] sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_814_p1;
wire   [136:0] r_V_fu_818_p2;
wire   [0:0] tmp_9_fu_830_p3;
wire   [136:0] r_V_1_fu_824_p2;
wire   [31:0] zext_ln662_fu_838_p1;
wire   [31:0] tmp_6_fu_842_p4;
wire   [8:0] add_ln49_1_fu_860_p2;
wire   [7:0] tmp_fu_866_p4;
wire   [7:0] tmp_1_fu_882_p4;
wire   [0:0] icmp_fu_876_p2;
wire   [0:0] icmp15_fu_892_p2;
wire   [0:0] cmp74_mid1_fu_905_p2;
wire   [0:0] cmp745_fu_911_p2;
wire   [0:0] select_ln46_1_fu_898_p3;
wire   [31:0] result_V_2_fu_936_p2;
wire   [31:0] result_V_fu_941_p3;
wire   [23:0] tmp_10_fu_947_p4;
wire   [0:0] icmp_ln81_fu_957_p2;
wire   [7:0] trunc_ln301_fu_963_p1;
wire   [0:0] and_ln70_fu_931_p2;
wire   [7:0] outval_V_fu_967_p3;
wire   [7:0] outval_V_1_fu_975_p3;
wire   [0:0] select_ln46_2_fu_917_p3;
wire   [8:0] grp_fu_1000_p0;
wire   [7:0] grp_fu_1000_p1;
wire   [11:0] grp_fu_1000_p2;
reg    grp_fu_389_ce;
reg    grp_fu_393_ce;
reg    grp_fu_396_ce;
reg    grp_fu_1000_ce;
reg   [4:0] ap_NS_fsm;
wire    ap_CS_fsm_state26;
wire    regslice_both_out_pix_V_data_V_U_apdone_blk;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    regslice_both_in_pix_V_data_V_U_apdone_blk;
wire   [23:0] in_pix_TDATA_int_regslice;
wire    in_pix_TVALID_int_regslice;
reg    in_pix_TREADY_int_regslice;
wire    regslice_both_in_pix_V_data_V_U_ack_in;
wire    regslice_both_in_pix_V_keep_V_U_apdone_blk;
wire   [2:0] in_pix_TKEEP_int_regslice;
wire    regslice_both_in_pix_V_keep_V_U_vld_out;
wire    regslice_both_in_pix_V_keep_V_U_ack_in;
wire    regslice_both_in_pix_V_strb_V_U_apdone_blk;
wire   [2:0] in_pix_TSTRB_int_regslice;
wire    regslice_both_in_pix_V_strb_V_U_vld_out;
wire    regslice_both_in_pix_V_strb_V_U_ack_in;
wire    regslice_both_in_pix_V_user_V_U_apdone_blk;
wire   [0:0] in_pix_TUSER_int_regslice;
wire    regslice_both_in_pix_V_user_V_U_vld_out;
wire    regslice_both_in_pix_V_user_V_U_ack_in;
wire    regslice_both_in_pix_V_last_V_U_apdone_blk;
wire   [0:0] in_pix_TLAST_int_regslice;
wire    regslice_both_in_pix_V_last_V_U_vld_out;
wire    regslice_both_in_pix_V_last_V_U_ack_in;
wire    regslice_both_in_pix_V_id_V_U_apdone_blk;
wire   [0:0] in_pix_TID_int_regslice;
wire    regslice_both_in_pix_V_id_V_U_vld_out;
wire    regslice_both_in_pix_V_id_V_U_ack_in;
wire    regslice_both_in_pix_V_dest_V_U_apdone_blk;
wire   [0:0] in_pix_TDEST_int_regslice;
wire    regslice_both_in_pix_V_dest_V_U_vld_out;
wire    regslice_both_in_pix_V_dest_V_U_ack_in;
wire   [23:0] out_pix_TDATA_int_regslice;
reg    out_pix_TVALID_int_regslice;
wire    out_pix_TREADY_int_regslice;
wire    regslice_both_out_pix_V_data_V_U_vld_out;
wire    regslice_both_out_pix_V_keep_V_U_apdone_blk;
wire    regslice_both_out_pix_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_keep_V_U_vld_out;
wire    regslice_both_out_pix_V_strb_V_U_apdone_blk;
wire    regslice_both_out_pix_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_strb_V_U_vld_out;
wire    regslice_both_out_pix_V_user_V_U_apdone_blk;
wire   [0:0] out_pix_TUSER_int_regslice;
wire    regslice_both_out_pix_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_user_V_U_vld_out;
wire    regslice_both_out_pix_V_last_V_U_apdone_blk;
wire    regslice_both_out_pix_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_last_V_U_vld_out;
wire    regslice_both_out_pix_V_id_V_U_apdone_blk;
wire    regslice_both_out_pix_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_id_V_U_vld_out;
wire    regslice_both_out_pix_V_dest_V_U_apdone_blk;
wire    regslice_both_out_pix_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_pix_V_dest_V_U_vld_out;
wire   [9:0] grp_fu_1000_p00;
wire   [9:0] grp_fu_1000_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter20 = 1'b0;
#0 ap_enable_reg_pp1_iter21 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter11 = 1'b0;
#0 ap_enable_reg_pp1_iter12 = 1'b0;
#0 ap_enable_reg_pp1_iter13 = 1'b0;
#0 ap_enable_reg_pp1_iter14 = 1'b0;
#0 ap_enable_reg_pp1_iter15 = 1'b0;
#0 ap_enable_reg_pp1_iter16 = 1'b0;
#0 ap_enable_reg_pp1_iter17 = 1'b0;
#0 ap_enable_reg_pp1_iter18 = 1'b0;
#0 ap_enable_reg_pp1_iter19 = 1'b0;
end

sobel_video_stream_line1_V #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line1_V_address0),
    .ce0(line1_V_ce0),
    .q0(line1_V_q0),
    .address1(line1_V_address1),
    .ce1(line1_V_ce1),
    .we1(line1_V_we1),
    .d1(line1_V_d1)
);

sobel_video_stream_line2_V #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address1(line2_V_address1),
    .ce1(line2_V_ce1),
    .we1(line2_V_we1),
    .d1(line2_V_d1),
    .q1(line2_V_q1)
);

sobel_video_stream_dadd_64ns_64ns_64_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_7_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_389_p0),
    .din1(grp_fu_389_p1),
    .ce(grp_fu_389_ce),
    .dout(grp_fu_389_p2)
);

sobel_video_stream_sitodp_32s_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_6_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_393_p0),
    .ce(grp_fu_393_ce),
    .dout(grp_fu_393_p1)
);

sobel_video_stream_sitodp_32s_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_6_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_396_p0),
    .ce(grp_fu_396_ce),
    .dout(grp_fu_396_p1)
);

sobel_video_stream_am_addmul_9ns_8ns_12ns_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
am_addmul_9ns_8ns_12ns_21_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1000_p0),
    .din1(grp_fu_1000_p1),
    .din2(grp_fu_1000_p2),
    .ce(grp_fu_1000_ce),
    .dout(grp_fu_1000_p3)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 24 ))
regslice_both_in_pix_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TDATA),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_data_V_U_ack_in),
    .data_out(in_pix_TDATA_int_regslice),
    .vld_out(in_pix_TVALID_int_regslice),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_data_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 3 ))
regslice_both_in_pix_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TKEEP),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_keep_V_U_ack_in),
    .data_out(in_pix_TKEEP_int_regslice),
    .vld_out(regslice_both_in_pix_V_keep_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_keep_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 3 ))
regslice_both_in_pix_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TSTRB),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_strb_V_U_ack_in),
    .data_out(in_pix_TSTRB_int_regslice),
    .vld_out(regslice_both_in_pix_V_strb_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_strb_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_pix_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TUSER),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_user_V_U_ack_in),
    .data_out(in_pix_TUSER_int_regslice),
    .vld_out(regslice_both_in_pix_V_user_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_user_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_pix_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TLAST),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_last_V_U_ack_in),
    .data_out(in_pix_TLAST_int_regslice),
    .vld_out(regslice_both_in_pix_V_last_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_last_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_pix_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TID),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_id_V_U_ack_in),
    .data_out(in_pix_TID_int_regslice),
    .vld_out(regslice_both_in_pix_V_id_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_id_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_pix_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_TDEST),
    .vld_in(in_pix_TVALID),
    .ack_in(regslice_both_in_pix_V_dest_V_U_ack_in),
    .data_out(in_pix_TDEST_int_regslice),
    .vld_out(regslice_both_in_pix_V_dest_V_U_vld_out),
    .ack_out(in_pix_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_pix_V_dest_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 24 ))
regslice_both_out_pix_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pix_TDATA_int_regslice),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(out_pix_TREADY_int_regslice),
    .data_out(out_pix_TDATA),
    .vld_out(regslice_both_out_pix_V_data_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_data_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 3 ))
regslice_both_out_pix_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(3'd7),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_keep_V_U_ack_in_dummy),
    .data_out(out_pix_TKEEP),
    .vld_out(regslice_both_out_pix_V_keep_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_keep_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 3 ))
regslice_both_out_pix_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(3'd7),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_strb_V_U_ack_in_dummy),
    .data_out(out_pix_TSTRB),
    .vld_out(regslice_both_out_pix_V_strb_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_strb_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_pix_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pix_TUSER_int_regslice),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_user_V_U_ack_in_dummy),
    .data_out(out_pix_TUSER),
    .vld_out(regslice_both_out_pix_V_user_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_user_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_pix_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pkt_last_V_reg_1064_pp1_iter19_reg),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_last_V_U_ack_in_dummy),
    .data_out(out_pix_TLAST),
    .vld_out(regslice_both_out_pix_V_last_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_last_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_pix_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_id_V_U_ack_in_dummy),
    .data_out(out_pix_TID),
    .vld_out(regslice_both_out_pix_V_id_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_id_V_U_apdone_blk)
);

sobel_video_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_pix_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_pix_TVALID_int_regslice),
    .ack_in(regslice_both_out_pix_V_dest_V_U_ack_in_dummy),
    .data_out(out_pix_TDEST),
    .vld_out(regslice_both_out_pix_V_dest_V_U_vld_out),
    .ack_out(out_pix_TREADY),
    .apdone_blk(regslice_both_out_pix_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter11 <= ap_enable_reg_pp1_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter12 <= ap_enable_reg_pp1_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter13 <= ap_enable_reg_pp1_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter14 <= ap_enable_reg_pp1_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter15 <= ap_enable_reg_pp1_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter16 <= ap_enable_reg_pp1_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter17 <= ap_enable_reg_pp1_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter18 <= ap_enable_reg_pp1_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter19 <= ap_enable_reg_pp1_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter20 <= ap_enable_reg_pp1_iter19;
        end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter19 == 1'b0) & (1'b1 == ap_condition_pp1_exit_iter20_state24)))) begin
            ap_enable_reg_pp1_iter20 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter21 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter20_state24))) begin
            ap_enable_reg_pp1_iter21 <= ap_enable_reg_pp1_iter19;
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter21 <= ap_enable_reg_pp1_iter20;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter21 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_reg_273 <= 10'd0;
    end else if (((icmp_ln39_fu_405_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_273 <= add_ln39_fu_399_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        indvar_flatten_reg_284 <= 19'd0;
    end else if (((icmp_ln49_fu_423_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        indvar_flatten_reg_284 <= add_ln49_fu_417_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        w01_V_1_reg_330 <= 8'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        w01_V_1_reg_330 <= w01_V_reg_341;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        w01_V_reg_341 <= 8'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        w01_V_reg_341 <= w02_V_reg_1080_pp1_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        w11_V_1_reg_354 <= 8'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        w11_V_1_reg_354 <= w11_V_reg_365;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        w11_V_reg_365 <= 8'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        w11_V_reg_365 <= w12_V_reg_1074_pp1_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        w21_V_2_reg_318 <= 8'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        w21_V_2_reg_318 <= w21_V_reg_306;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        w21_V_reg_306 <= 8'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        w21_V_reg_306 <= w22_V_reg_1087;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_reg_295 <= 10'd0;
    end else if (((icmp_ln49_fu_423_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        x_reg_295 <= add_ln50_fu_519_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_reg_378 <= 9'd0;
    end else if (((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (ap_enable_reg_pp1_iter20 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        y_reg_378 <= select_ln49_fu_924_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_423_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        add_ln208_reg_1038 <= add_ln208_fu_485_p2;
        g_reg_1033 <= {{in_pix_TDATA_int_regslice[15:8]}};
        icmp_ln50_reg_1026 <= icmp_ln50_fu_429_p2;
        icmp_ln70_reg_1054 <= icmp_ln70_fu_501_p2;
        icmp_ln95_reg_1059 <= icmp_ln95_fu_507_p2;
        line1_V_addr_1_reg_1043 <= zext_ln50_fu_443_p1;
        line2_V_addr_1_reg_1049 <= zext_ln50_fu_443_p1;
        out_pkt_last_V_reg_1064 <= out_pkt_last_V_fu_513_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln49_reg_1022_pp1_iter3_reg == 1'd0))) begin
        add_ln73_reg_1093 <= add_ln73_fu_579_p2;
        sub_ln78_reg_1098 <= sub_ln78_fu_625_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln49_reg_1022_pp1_iter17_reg == 1'd0))) begin
        dc_2_reg_1143 <= grp_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        gx_reg_1103 <= gx_fu_670_p2;
        gy_reg_1108 <= gy_fu_681_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln49_reg_1022 <= icmp_ln49_fu_423_p2;
        icmp_ln49_reg_1022_pp1_iter1_reg <= icmp_ln49_reg_1022;
        icmp_ln50_reg_1026_pp1_iter1_reg <= icmp_ln50_reg_1026;
        icmp_ln70_reg_1054_pp1_iter1_reg <= icmp_ln70_reg_1054;
        icmp_ln95_reg_1059_pp1_iter1_reg <= icmp_ln95_reg_1059;
        line1_V_addr_1_reg_1043_pp1_iter1_reg <= line1_V_addr_1_reg_1043;
        out_pkt_last_V_reg_1064_pp1_iter1_reg <= out_pkt_last_V_reg_1064;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln49_reg_1022_pp1_iter10_reg <= icmp_ln49_reg_1022_pp1_iter9_reg;
        icmp_ln49_reg_1022_pp1_iter11_reg <= icmp_ln49_reg_1022_pp1_iter10_reg;
        icmp_ln49_reg_1022_pp1_iter12_reg <= icmp_ln49_reg_1022_pp1_iter11_reg;
        icmp_ln49_reg_1022_pp1_iter13_reg <= icmp_ln49_reg_1022_pp1_iter12_reg;
        icmp_ln49_reg_1022_pp1_iter14_reg <= icmp_ln49_reg_1022_pp1_iter13_reg;
        icmp_ln49_reg_1022_pp1_iter15_reg <= icmp_ln49_reg_1022_pp1_iter14_reg;
        icmp_ln49_reg_1022_pp1_iter16_reg <= icmp_ln49_reg_1022_pp1_iter15_reg;
        icmp_ln49_reg_1022_pp1_iter17_reg <= icmp_ln49_reg_1022_pp1_iter16_reg;
        icmp_ln49_reg_1022_pp1_iter18_reg <= icmp_ln49_reg_1022_pp1_iter17_reg;
        icmp_ln49_reg_1022_pp1_iter19_reg <= icmp_ln49_reg_1022_pp1_iter18_reg;
        icmp_ln49_reg_1022_pp1_iter20_reg <= icmp_ln49_reg_1022_pp1_iter19_reg;
        icmp_ln49_reg_1022_pp1_iter2_reg <= icmp_ln49_reg_1022_pp1_iter1_reg;
        icmp_ln49_reg_1022_pp1_iter3_reg <= icmp_ln49_reg_1022_pp1_iter2_reg;
        icmp_ln49_reg_1022_pp1_iter4_reg <= icmp_ln49_reg_1022_pp1_iter3_reg;
        icmp_ln49_reg_1022_pp1_iter5_reg <= icmp_ln49_reg_1022_pp1_iter4_reg;
        icmp_ln49_reg_1022_pp1_iter6_reg <= icmp_ln49_reg_1022_pp1_iter5_reg;
        icmp_ln49_reg_1022_pp1_iter7_reg <= icmp_ln49_reg_1022_pp1_iter6_reg;
        icmp_ln49_reg_1022_pp1_iter8_reg <= icmp_ln49_reg_1022_pp1_iter7_reg;
        icmp_ln49_reg_1022_pp1_iter9_reg <= icmp_ln49_reg_1022_pp1_iter8_reg;
        icmp_ln50_reg_1026_pp1_iter10_reg <= icmp_ln50_reg_1026_pp1_iter9_reg;
        icmp_ln50_reg_1026_pp1_iter11_reg <= icmp_ln50_reg_1026_pp1_iter10_reg;
        icmp_ln50_reg_1026_pp1_iter12_reg <= icmp_ln50_reg_1026_pp1_iter11_reg;
        icmp_ln50_reg_1026_pp1_iter13_reg <= icmp_ln50_reg_1026_pp1_iter12_reg;
        icmp_ln50_reg_1026_pp1_iter14_reg <= icmp_ln50_reg_1026_pp1_iter13_reg;
        icmp_ln50_reg_1026_pp1_iter15_reg <= icmp_ln50_reg_1026_pp1_iter14_reg;
        icmp_ln50_reg_1026_pp1_iter16_reg <= icmp_ln50_reg_1026_pp1_iter15_reg;
        icmp_ln50_reg_1026_pp1_iter17_reg <= icmp_ln50_reg_1026_pp1_iter16_reg;
        icmp_ln50_reg_1026_pp1_iter18_reg <= icmp_ln50_reg_1026_pp1_iter17_reg;
        icmp_ln50_reg_1026_pp1_iter19_reg <= icmp_ln50_reg_1026_pp1_iter18_reg;
        icmp_ln50_reg_1026_pp1_iter2_reg <= icmp_ln50_reg_1026_pp1_iter1_reg;
        icmp_ln50_reg_1026_pp1_iter3_reg <= icmp_ln50_reg_1026_pp1_iter2_reg;
        icmp_ln50_reg_1026_pp1_iter4_reg <= icmp_ln50_reg_1026_pp1_iter3_reg;
        icmp_ln50_reg_1026_pp1_iter5_reg <= icmp_ln50_reg_1026_pp1_iter4_reg;
        icmp_ln50_reg_1026_pp1_iter6_reg <= icmp_ln50_reg_1026_pp1_iter5_reg;
        icmp_ln50_reg_1026_pp1_iter7_reg <= icmp_ln50_reg_1026_pp1_iter6_reg;
        icmp_ln50_reg_1026_pp1_iter8_reg <= icmp_ln50_reg_1026_pp1_iter7_reg;
        icmp_ln50_reg_1026_pp1_iter9_reg <= icmp_ln50_reg_1026_pp1_iter8_reg;
        icmp_ln70_reg_1054_pp1_iter10_reg <= icmp_ln70_reg_1054_pp1_iter9_reg;
        icmp_ln70_reg_1054_pp1_iter11_reg <= icmp_ln70_reg_1054_pp1_iter10_reg;
        icmp_ln70_reg_1054_pp1_iter12_reg <= icmp_ln70_reg_1054_pp1_iter11_reg;
        icmp_ln70_reg_1054_pp1_iter13_reg <= icmp_ln70_reg_1054_pp1_iter12_reg;
        icmp_ln70_reg_1054_pp1_iter14_reg <= icmp_ln70_reg_1054_pp1_iter13_reg;
        icmp_ln70_reg_1054_pp1_iter15_reg <= icmp_ln70_reg_1054_pp1_iter14_reg;
        icmp_ln70_reg_1054_pp1_iter16_reg <= icmp_ln70_reg_1054_pp1_iter15_reg;
        icmp_ln70_reg_1054_pp1_iter17_reg <= icmp_ln70_reg_1054_pp1_iter16_reg;
        icmp_ln70_reg_1054_pp1_iter18_reg <= icmp_ln70_reg_1054_pp1_iter17_reg;
        icmp_ln70_reg_1054_pp1_iter19_reg <= icmp_ln70_reg_1054_pp1_iter18_reg;
        icmp_ln70_reg_1054_pp1_iter2_reg <= icmp_ln70_reg_1054_pp1_iter1_reg;
        icmp_ln70_reg_1054_pp1_iter3_reg <= icmp_ln70_reg_1054_pp1_iter2_reg;
        icmp_ln70_reg_1054_pp1_iter4_reg <= icmp_ln70_reg_1054_pp1_iter3_reg;
        icmp_ln70_reg_1054_pp1_iter5_reg <= icmp_ln70_reg_1054_pp1_iter4_reg;
        icmp_ln70_reg_1054_pp1_iter6_reg <= icmp_ln70_reg_1054_pp1_iter5_reg;
        icmp_ln70_reg_1054_pp1_iter7_reg <= icmp_ln70_reg_1054_pp1_iter6_reg;
        icmp_ln70_reg_1054_pp1_iter8_reg <= icmp_ln70_reg_1054_pp1_iter7_reg;
        icmp_ln70_reg_1054_pp1_iter9_reg <= icmp_ln70_reg_1054_pp1_iter8_reg;
        icmp_ln95_reg_1059_pp1_iter10_reg <= icmp_ln95_reg_1059_pp1_iter9_reg;
        icmp_ln95_reg_1059_pp1_iter11_reg <= icmp_ln95_reg_1059_pp1_iter10_reg;
        icmp_ln95_reg_1059_pp1_iter12_reg <= icmp_ln95_reg_1059_pp1_iter11_reg;
        icmp_ln95_reg_1059_pp1_iter13_reg <= icmp_ln95_reg_1059_pp1_iter12_reg;
        icmp_ln95_reg_1059_pp1_iter14_reg <= icmp_ln95_reg_1059_pp1_iter13_reg;
        icmp_ln95_reg_1059_pp1_iter15_reg <= icmp_ln95_reg_1059_pp1_iter14_reg;
        icmp_ln95_reg_1059_pp1_iter16_reg <= icmp_ln95_reg_1059_pp1_iter15_reg;
        icmp_ln95_reg_1059_pp1_iter17_reg <= icmp_ln95_reg_1059_pp1_iter16_reg;
        icmp_ln95_reg_1059_pp1_iter18_reg <= icmp_ln95_reg_1059_pp1_iter17_reg;
        icmp_ln95_reg_1059_pp1_iter19_reg <= icmp_ln95_reg_1059_pp1_iter18_reg;
        icmp_ln95_reg_1059_pp1_iter2_reg <= icmp_ln95_reg_1059_pp1_iter1_reg;
        icmp_ln95_reg_1059_pp1_iter3_reg <= icmp_ln95_reg_1059_pp1_iter2_reg;
        icmp_ln95_reg_1059_pp1_iter4_reg <= icmp_ln95_reg_1059_pp1_iter3_reg;
        icmp_ln95_reg_1059_pp1_iter5_reg <= icmp_ln95_reg_1059_pp1_iter4_reg;
        icmp_ln95_reg_1059_pp1_iter6_reg <= icmp_ln95_reg_1059_pp1_iter5_reg;
        icmp_ln95_reg_1059_pp1_iter7_reg <= icmp_ln95_reg_1059_pp1_iter6_reg;
        icmp_ln95_reg_1059_pp1_iter8_reg <= icmp_ln95_reg_1059_pp1_iter7_reg;
        icmp_ln95_reg_1059_pp1_iter9_reg <= icmp_ln95_reg_1059_pp1_iter8_reg;
        line1_V_addr_1_reg_1043_pp1_iter2_reg <= line1_V_addr_1_reg_1043_pp1_iter1_reg;
        line1_V_addr_1_reg_1043_pp1_iter3_reg <= line1_V_addr_1_reg_1043_pp1_iter2_reg;
        out_pkt_last_V_reg_1064_pp1_iter10_reg <= out_pkt_last_V_reg_1064_pp1_iter9_reg;
        out_pkt_last_V_reg_1064_pp1_iter11_reg <= out_pkt_last_V_reg_1064_pp1_iter10_reg;
        out_pkt_last_V_reg_1064_pp1_iter12_reg <= out_pkt_last_V_reg_1064_pp1_iter11_reg;
        out_pkt_last_V_reg_1064_pp1_iter13_reg <= out_pkt_last_V_reg_1064_pp1_iter12_reg;
        out_pkt_last_V_reg_1064_pp1_iter14_reg <= out_pkt_last_V_reg_1064_pp1_iter13_reg;
        out_pkt_last_V_reg_1064_pp1_iter15_reg <= out_pkt_last_V_reg_1064_pp1_iter14_reg;
        out_pkt_last_V_reg_1064_pp1_iter16_reg <= out_pkt_last_V_reg_1064_pp1_iter15_reg;
        out_pkt_last_V_reg_1064_pp1_iter17_reg <= out_pkt_last_V_reg_1064_pp1_iter16_reg;
        out_pkt_last_V_reg_1064_pp1_iter18_reg <= out_pkt_last_V_reg_1064_pp1_iter17_reg;
        out_pkt_last_V_reg_1064_pp1_iter19_reg <= out_pkt_last_V_reg_1064_pp1_iter18_reg;
        out_pkt_last_V_reg_1064_pp1_iter2_reg <= out_pkt_last_V_reg_1064_pp1_iter1_reg;
        out_pkt_last_V_reg_1064_pp1_iter3_reg <= out_pkt_last_V_reg_1064_pp1_iter2_reg;
        out_pkt_last_V_reg_1064_pp1_iter4_reg <= out_pkt_last_V_reg_1064_pp1_iter3_reg;
        out_pkt_last_V_reg_1064_pp1_iter5_reg <= out_pkt_last_V_reg_1064_pp1_iter4_reg;
        out_pkt_last_V_reg_1064_pp1_iter6_reg <= out_pkt_last_V_reg_1064_pp1_iter5_reg;
        out_pkt_last_V_reg_1064_pp1_iter7_reg <= out_pkt_last_V_reg_1064_pp1_iter6_reg;
        out_pkt_last_V_reg_1064_pp1_iter8_reg <= out_pkt_last_V_reg_1064_pp1_iter7_reg;
        out_pkt_last_V_reg_1064_pp1_iter9_reg <= out_pkt_last_V_reg_1064_pp1_iter8_reg;
        w02_V_reg_1080_pp1_iter3_reg <= w02_V_reg_1080;
        w02_V_reg_1080_pp1_iter4_reg <= w02_V_reg_1080_pp1_iter3_reg;
        w12_V_reg_1074_pp1_iter2_reg <= w12_V_reg_1074;
        w12_V_reg_1074_pp1_iter3_reg <= w12_V_reg_1074_pp1_iter2_reg;
        w12_V_reg_1074_pp1_iter4_reg <= w12_V_reg_1074_pp1_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln49_reg_1022_pp1_iter18_reg == 1'd0))) begin
        p_Result_2_reg_1148 <= data_V_2_fu_735_p1[32'd63];
        val_reg_1153 <= val_fu_852_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln49_reg_1022_pp1_iter10_reg == 1'd0))) begin
        trunc_ln368_1_reg_1128 <= trunc_ln368_1_fu_707_p1;
        trunc_ln368_reg_1123 <= trunc_ln368_fu_699_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter1_reg == 1'd0))) begin
        w02_V_reg_1080 <= line2_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_1022 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        w12_V_reg_1074 <= line1_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter3_reg == 1'd0))) begin
        w22_V_reg_1087 <= {{grp_fu_1000_p3[19:12]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter20 == 1'b1) & (ap_enable_reg_pp1_iter19 == 1'b0))) begin
        ap_condition_pp1_exit_iter20_state24 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter20_state24 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln49_fu_423_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter21 == 1'b0) & (ap_enable_reg_pp1_iter20 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter19 == 1'b0) & (ap_enable_reg_pp1_iter18 == 1'b0) & (ap_enable_reg_pp1_iter17 == 1'b0) & (ap_enable_reg_pp1_iter16 == 1'b0) & (ap_enable_reg_pp1_iter15 == 1'b0) & (ap_enable_reg_pp1_iter14 == 1'b0) & (ap_enable_reg_pp1_iter13 == 1'b0) & (ap_enable_reg_pp1_iter12 == 1'b0) & (ap_enable_reg_pp1_iter11 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        ap_phi_mux_w01_V_1_phi_fu_334_p4 = w01_V_reg_341;
    end else begin
        ap_phi_mux_w01_V_1_phi_fu_334_p4 = w01_V_1_reg_330;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        ap_phi_mux_w01_V_phi_fu_346_p4 = w02_V_reg_1080_pp1_iter4_reg;
    end else begin
        ap_phi_mux_w01_V_phi_fu_346_p4 = w01_V_reg_341;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        ap_phi_mux_w11_V_1_phi_fu_358_p4 = w11_V_reg_365;
    end else begin
        ap_phi_mux_w11_V_1_phi_fu_358_p4 = w11_V_1_reg_354;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        ap_phi_mux_w21_V_2_phi_fu_322_p4 = w21_V_reg_306;
    end else begin
        ap_phi_mux_w21_V_2_phi_fu_322_p4 = w21_V_2_reg_318;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter4_reg == 1'd0))) begin
        ap_phi_mux_w21_V_phi_fu_310_p4 = w22_V_reg_1087;
    end else begin
        ap_phi_mux_w21_V_phi_fu_310_p4 = w21_V_reg_306;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_1000_ce = 1'b1;
    end else begin
        grp_fu_1000_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_389_ce = 1'b1;
    end else begin
        grp_fu_389_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_393_ce = 1'b1;
    end else begin
        grp_fu_393_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_396_ce = 1'b1;
    end else begin
        grp_fu_396_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln49_fu_423_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        in_pix_TDATA_blk_n = in_pix_TVALID_int_regslice;
    end else begin
        in_pix_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln49_fu_423_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        in_pix_TREADY_int_regslice = 1'b1;
    end else begin
        in_pix_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        line1_V_address1 = line1_V_addr_1_reg_1043_pp1_iter3_reg;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line1_V_address1 = zext_ln39_fu_411_p1;
    end else begin
        line1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line1_V_ce0 = 1'b1;
    end else begin
        line1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter4 == 1'b1)))) begin
        line1_V_ce1 = 1'b1;
    end else begin
        line1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        line1_V_d1 = {{grp_fu_1000_p3[19:12]}};
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line1_V_d1 = 8'd0;
    end else begin
        line1_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln39_fu_405_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln49_reg_1022_pp1_iter3_reg == 1'd0)))) begin
        line1_V_we1 = 1'b1;
    end else begin
        line1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_1022 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line2_V_address1 = line2_V_addr_1_reg_1049;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line2_V_address1 = zext_ln39_fu_411_p1;
    end else begin
        line2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln49_reg_1022 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        line2_V_ce1 = 1'b1;
    end else begin
        line2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_1022 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line2_V_d1 = line1_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line2_V_d1 = 8'd0;
    end else begin
        line2_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln39_fu_405_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln49_reg_1022 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        line2_V_we1 = 1'b1;
    end else begin
        line2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln49_reg_1022_pp1_iter20_reg == 1'd0) & (ap_enable_reg_pp1_iter21 == 1'b1) & (1'b0 == ap_block_pp1_stage0)) | ((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (ap_enable_reg_pp1_iter20 == 1'b1) & (1'b0 == ap_block_pp1_stage0)))) begin
        out_pix_TDATA_blk_n = out_pix_TREADY_int_regslice;
    end else begin
        out_pix_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (ap_enable_reg_pp1_iter20 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        out_pix_TVALID_int_regslice = 1'b1;
    end else begin
        out_pix_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln39_fu_405_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_enable_reg_pp1_iter20 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter19 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter20 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter19 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((regslice_both_out_pix_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln208_fu_485_p2 = (zext_ln208_fu_477_p1 + zext_ln208_2_fu_481_p1);

assign add_ln39_fu_399_p2 = (i_reg_273 + 10'd1);

assign add_ln49_1_fu_860_p2 = (y_reg_378 + 9'd1);

assign add_ln49_fu_417_p2 = (indvar_flatten_reg_284 + 19'd1);

assign add_ln50_fu_519_p2 = (select_ln46_fu_435_p3 + 10'd1);

assign add_ln510_fu_778_p2 = ($signed(zext_ln510_fu_774_p1) + $signed(12'd3073));

assign add_ln73_1_fu_569_p2 = (zext_ln72_1_fu_545_p1 + zext_ln74_2_fu_565_p1);

assign add_ln73_fu_579_p2 = (zext_ln73_4_fu_575_p1 + zext_ln73_2_fu_557_p1);

assign add_ln74_fu_660_p2 = (zext_ln74_fu_644_p1 + zext_ln73_1_fu_634_p1);

assign add_ln77_fu_609_p2 = (zext_ln77_fu_605_p1 + zext_ln74_1_fu_561_p1);

assign add_ln78_fu_676_p2 = (sub_ln78_reg_1098 + zext_ln73_3_fu_648_p1);

assign and_ln70_fu_931_p2 = (select_ln46_1_fu_898_p3 & icmp_ln70_reg_1054_pp1_iter19_reg);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((icmp_ln49_reg_1022_pp1_iter20_reg == 1'd0) & (ap_enable_reg_pp1_iter21 == 1'b1) & (out_pix_TREADY_int_regslice == 1'b0)) | ((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (ap_enable_reg_pp1_iter20 == 1'b1) & (out_pix_TREADY_int_regslice == 1'b0)) | ((icmp_ln49_fu_423_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (in_pix_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((ap_enable_reg_pp1_iter21 == 1'b1) & ((1'b1 == ap_block_state25_io) | ((icmp_ln49_reg_1022_pp1_iter20_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp1_iter20 == 1'b1) & ((1'b1 == ap_block_state24_io) | ((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0)))) | ((icmp_ln49_fu_423_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (in_pix_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((ap_enable_reg_pp1_iter21 == 1'b1) & ((1'b1 == ap_block_state25_io) | ((icmp_ln49_reg_1022_pp1_iter20_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp1_iter20 == 1'b1) & ((1'b1 == ap_block_state24_io) | ((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0)))) | ((icmp_ln49_fu_423_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (in_pix_TVALID_int_regslice == 1'b0)));
end

assign ap_block_state10_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp1_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp1_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp1_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp1_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp1_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp1_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp1_stage0_iter19 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state24_io = ((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state24_pp1_stage0_iter20 = ((icmp_ln49_reg_1022_pp1_iter19_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state25_io = ((icmp_ln49_reg_1022_pp1_iter20_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state25_pp1_stage0_iter21 = ((icmp_ln49_reg_1022_pp1_iter20_reg == 1'd0) & (out_pix_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp1_stage0_iter0 = ((icmp_ln49_fu_423_p2 == 1'd0) & (in_pix_TVALID_int_regslice == 1'b0));
end

assign ap_block_state5_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b_fu_473_p1 = in_pix_TDATA_int_regslice[7:0];

assign cmp745_fu_911_p2 = ((y_reg_378 == 9'd0) ? 1'b1 : 1'b0);

assign cmp74_mid1_fu_905_p2 = ((add_ln49_1_fu_860_p2 == 9'd0) ? 1'b1 : 1'b0);

assign data_V_1_fu_703_p1 = grp_fu_396_p1;

assign data_V_2_fu_735_p1 = dc_2_reg_1143;

assign data_V_fu_695_p1 = grp_fu_393_p1;

assign grp_fu_1000_p0 = grp_fu_1000_p00;

assign grp_fu_1000_p00 = add_ln208_reg_1038;

assign grp_fu_1000_p1 = grp_fu_1000_p10;

assign grp_fu_1000_p10 = g_reg_1033;

assign grp_fu_1000_p2 = 21'd1366;

assign grp_fu_389_p0 = p_Result_s_fu_711_p3;

assign grp_fu_389_p1 = p_Result_1_fu_723_p3;

assign grp_fu_393_p0 = $signed(gx_reg_1103);

assign grp_fu_396_p0 = $signed(gy_reg_1108);

assign gx_fu_670_p2 = (zext_ln74_3_fu_666_p1 + sub_ln73_fu_654_p2);

assign gy_fu_681_p2 = (add_ln78_fu_676_p2 - zext_ln73_fu_631_p1);

assign icmp15_fu_892_p2 = ((tmp_1_fu_882_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_fu_876_p2 = ((tmp_fu_866_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_405_p2 = ((i_reg_273 == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_423_p2 = ((indvar_flatten_reg_284 == 19'd307200) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_429_p2 = ((x_reg_295 == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_501_p2 = ((tmp_2_fu_491_p4 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_957_p2 = (($signed(tmp_10_fu_947_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_507_p2 = ((select_ln46_fu_435_p3 == 10'd0) ? 1'b1 : 1'b0);

assign in_pix_TREADY = regslice_both_in_pix_V_data_V_U_ack_in;

assign isNeg_fu_784_p3 = add_ln510_fu_778_p2[32'd11];

assign line1_V_address0 = zext_ln50_fu_443_p1;

assign mantissa_fu_760_p4 = {{{{1'd1}, {tmp_12_fu_756_p1}}}, {1'd0}};

assign out_pix_TDATA_int_regslice = {{{outval_V_1_fu_975_p3}, {outval_V_1_fu_975_p3}}, {outval_V_1_fu_975_p3}};

assign out_pix_TUSER_int_regslice = (select_ln46_2_fu_917_p3 & icmp_ln95_reg_1059_pp1_iter19_reg);

assign out_pix_TVALID = regslice_both_out_pix_V_data_V_U_vld_out;

assign out_pkt_last_V_fu_513_p2 = ((select_ln46_fu_435_p3 == 10'd639) ? 1'b1 : 1'b0);

assign outval_V_1_fu_975_p3 = ((and_ln70_fu_931_p2[0:0] == 1'b1) ? outval_V_fu_967_p3 : 8'd0);

assign outval_V_fu_967_p3 = ((icmp_ln81_fu_957_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln301_fu_963_p1);

assign p_Result_1_fu_723_p3 = {{1'd0}, {trunc_ln368_1_reg_1128}};

assign p_Result_s_fu_711_p3 = {{1'd0}, {trunc_ln368_reg_1123}};

assign r_V_1_fu_824_p2 = zext_ln15_fu_770_p1 << sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_814_p1;

assign r_V_fu_818_p2 = zext_ln15_fu_770_p1 >> sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_814_p1;

assign r_fu_453_p4 = {{in_pix_TDATA_int_regslice[23:16]}};

assign result_V_2_fu_936_p2 = (32'd0 - val_reg_1153);

assign result_V_fu_941_p3 = ((p_Result_2_reg_1148[0:0] == 1'b1) ? result_V_2_fu_936_p2 : val_reg_1153);

assign select_ln46_1_fu_898_p3 = ((icmp_ln50_reg_1026_pp1_iter19_reg[0:0] == 1'b1) ? icmp_fu_876_p2 : icmp15_fu_892_p2);

assign select_ln46_2_fu_917_p3 = ((icmp_ln50_reg_1026_pp1_iter19_reg[0:0] == 1'b1) ? cmp74_mid1_fu_905_p2 : cmp745_fu_911_p2);

assign select_ln46_fu_435_p3 = ((icmp_ln50_fu_429_p2[0:0] == 1'b1) ? 10'd0 : x_reg_295);

assign select_ln49_fu_924_p3 = ((icmp_ln50_reg_1026_pp1_iter19_reg[0:0] == 1'b1) ? add_ln49_1_fu_860_p2 : y_reg_378);

assign sext_ln1311_fu_798_p1 = $signed(sub_ln1311_fu_792_p2);

assign sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_814_p1 = $unsigned(sh_prom_i_i_i_i_i_cast_cast_cast_fu_810_p1);

assign sh_prom_i_i_i_i_i_cast_cast_cast_fu_810_p1 = $signed(ush_fu_802_p3);

assign shl_ln1_fu_585_p3 = {{ap_phi_mux_w01_V_phi_fu_346_p4}, {1'd0}};

assign shl_ln2_fu_597_p3 = {{ap_phi_mux_w21_V_phi_fu_310_p4}, {1'd0}};

assign shl_ln73_1_fu_637_p3 = {{w12_V_reg_1074_pp1_iter4_reg}, {1'd0}};

assign shl_ln_fu_549_p3 = {{ap_phi_mux_w11_V_1_phi_fu_358_p4}, {1'd0}};

assign sub_ln1311_fu_792_p2 = (11'd1023 - tmp_11_fu_746_p4);

assign sub_ln73_fu_654_p2 = (zext_ln73_3_fu_648_p1 - zext_ln73_5_fu_651_p1);

assign sub_ln77_fu_619_p2 = (zext_ln77_1_fu_615_p1 - zext_ln72_fu_541_p1);

assign sub_ln78_fu_625_p2 = (sub_ln77_fu_619_p2 - zext_ln78_fu_593_p1);

assign tmp_10_fu_947_p4 = {{result_V_fu_941_p3[31:8]}};

assign tmp_11_fu_746_p4 = {{data_V_2_fu_735_p1[62:52]}};

assign tmp_12_fu_756_p1 = data_V_2_fu_735_p1[51:0];

assign tmp_1_fu_882_p4 = {{y_reg_378[8:1]}};

assign tmp_2_fu_491_p4 = {{select_ln46_fu_435_p3[9:1]}};

assign tmp_6_fu_842_p4 = {{r_V_1_fu_824_p2[84:53]}};

assign tmp_9_fu_830_p3 = r_V_fu_818_p2[32'd53];

assign tmp_fu_866_p4 = {{add_ln49_1_fu_860_p2[8:1]}};

assign trunc_ln301_fu_963_p1 = result_V_fu_941_p3[7:0];

assign trunc_ln368_1_fu_707_p1 = data_V_1_fu_703_p1[62:0];

assign trunc_ln368_fu_699_p1 = data_V_fu_695_p1[62:0];

assign ush_fu_802_p3 = ((isNeg_fu_784_p3[0:0] == 1'b1) ? sext_ln1311_fu_798_p1 : add_ln510_fu_778_p2);

assign val_fu_852_p3 = ((isNeg_fu_784_p3[0:0] == 1'b1) ? zext_ln662_fu_838_p1 : tmp_6_fu_842_p4);

assign zext_ln15_fu_770_p1 = mantissa_fu_760_p4;

assign zext_ln208_2_fu_481_p1 = b_fu_473_p1;

assign zext_ln208_fu_477_p1 = r_fu_453_p4;

assign zext_ln39_fu_411_p1 = i_reg_273;

assign zext_ln50_fu_443_p1 = select_ln46_fu_435_p3;

assign zext_ln510_fu_774_p1 = tmp_11_fu_746_p4;

assign zext_ln662_fu_838_p1 = tmp_9_fu_830_p3;

assign zext_ln72_1_fu_545_p1 = ap_phi_mux_w01_V_1_phi_fu_334_p4;

assign zext_ln72_fu_541_p1 = ap_phi_mux_w01_V_1_phi_fu_334_p4;

assign zext_ln73_1_fu_634_p1 = w02_V_reg_1080_pp1_iter4_reg;

assign zext_ln73_2_fu_557_p1 = shl_ln_fu_549_p3;

assign zext_ln73_3_fu_648_p1 = w22_V_reg_1087;

assign zext_ln73_4_fu_575_p1 = add_ln73_1_fu_569_p2;

assign zext_ln73_5_fu_651_p1 = add_ln73_reg_1093;

assign zext_ln73_fu_631_p1 = w02_V_reg_1080_pp1_iter4_reg;

assign zext_ln74_1_fu_561_p1 = ap_phi_mux_w21_V_2_phi_fu_322_p4;

assign zext_ln74_2_fu_565_p1 = ap_phi_mux_w21_V_2_phi_fu_322_p4;

assign zext_ln74_3_fu_666_p1 = add_ln74_fu_660_p2;

assign zext_ln74_fu_644_p1 = shl_ln73_1_fu_637_p3;

assign zext_ln77_1_fu_615_p1 = add_ln77_fu_609_p2;

assign zext_ln77_fu_605_p1 = shl_ln2_fu_597_p3;

assign zext_ln78_fu_593_p1 = shl_ln1_fu_585_p3;

endmodule //sobel_video_stream
