-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_hw_stream is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_pix_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_pix_TVALID : IN STD_LOGIC;
    in_pix_TREADY : OUT STD_LOGIC;
    in_pix_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    in_pix_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    in_pix_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_pix_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_pix_TVALID : OUT STD_LOGIC;
    out_pix_TREADY : IN STD_LOGIC;
    out_pix_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_pix_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_pix_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of sobel_hw_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sobel_hw_stream_sobel_hw_stream,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=65685,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1358,HLS_SYN_LUT=2990,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv17_10000 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_FF : STD_LOGIC_VECTOR (8 downto 0) := "011111111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal init_done : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal line1_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line1_V_ce0 : STD_LOGIC;
    signal line1_V_we0 : STD_LOGIC;
    signal line1_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line1_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line2_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line2_V_ce0 : STD_LOGIC;
    signal line2_V_we0 : STD_LOGIC;
    signal line2_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line2_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal line2_V_ce1 : STD_LOGIC;
    signal line2_V_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln38_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp1_iter17 : STD_LOGIC := '0';
    signal icmp_ln38_reg_896 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp1_iter18 : STD_LOGIC := '0';
    signal icmp_ln38_reg_896_pp1_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_220 : STD_LOGIC_VECTOR (16 downto 0);
    signal x_reg_231 : STD_LOGIC_VECTOR (8 downto 0);
    signal w21_V_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal w01_V_1_reg_254 : STD_LOGIC_VECTOR (7 downto 0);
    signal w01_V_reg_265 : STD_LOGIC_VECTOR (7 downto 0);
    signal w11_V_1_reg_278 : STD_LOGIC_VECTOR (7 downto 0);
    signal w11_V_reg_289 : STD_LOGIC_VECTOR (7 downto 0);
    signal w21_V_2_reg_302 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_reg_314 : STD_LOGIC_VECTOR (8 downto 0);
    signal init_done_load_load_fu_335_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal init_done_load_reg_879 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln26_fu_339_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln38_fu_363_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state4_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp1_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp1_stage0_iter3 : BOOLEAN;
    signal ap_block_state8_pp1_stage0_iter4 : BOOLEAN;
    signal ap_block_state9_pp1_stage0_iter5 : BOOLEAN;
    signal ap_block_state10_pp1_stage0_iter6 : BOOLEAN;
    signal ap_block_state11_pp1_stage0_iter7 : BOOLEAN;
    signal ap_block_state12_pp1_stage0_iter8 : BOOLEAN;
    signal ap_block_state13_pp1_stage0_iter9 : BOOLEAN;
    signal ap_block_state14_pp1_stage0_iter10 : BOOLEAN;
    signal ap_block_state15_pp1_stage0_iter11 : BOOLEAN;
    signal ap_block_state16_pp1_stage0_iter12 : BOOLEAN;
    signal ap_block_state17_pp1_stage0_iter13 : BOOLEAN;
    signal ap_block_state18_pp1_stage0_iter14 : BOOLEAN;
    signal ap_block_state19_pp1_stage0_iter15 : BOOLEAN;
    signal ap_block_state20_pp1_stage0_iter16 : BOOLEAN;
    signal ap_block_state21_pp1_stage0_iter17 : BOOLEAN;
    signal ap_block_state21_io : BOOLEAN;
    signal ap_block_state22_pp1_stage0_iter18 : BOOLEAN;
    signal ap_block_state22_io : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal icmp_ln38_reg_896_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_896_pp1_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_900_pp1_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal w22_V_reg_907 : STD_LOGIC_VECTOR (7 downto 0);
    signal w22_V_reg_907_pp1_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal line2_V_addr_1_reg_919 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln60_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_925_pp1_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_930_pp1_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln39_fu_422_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal w12_V_reg_940 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal w02_V_reg_946 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln64_1_fu_448_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln64_1_reg_953 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln63_fu_462_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln63_reg_958 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln67_1_fu_502_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln67_1_reg_963 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_fu_550_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_reg_968 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_fu_570_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_reg_973 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln368_fu_588_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln368_reg_988 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln368_1_fu_596_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln368_1_reg_993 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_fu_325_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal dc_2_reg_1008 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_2_reg_1013 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_fu_741_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_1018 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln38_fu_813_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp1_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter16 : STD_LOGIC := '0';
    signal ap_condition_pp1_exit_iter17_state21 : STD_LOGIC;
    signal i_reg_209 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln26_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_w21_V_phi_fu_246_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w01_V_1_phi_fu_258_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w01_V_phi_fu_270_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w11_V_1_phi_fu_282_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w21_V_2_phi_fu_306_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln26_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln39_fu_389_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal grp_fu_325_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_329_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_332_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln36_fu_381_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_400_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_436_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln62_1_fu_432_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln63_1_fu_452_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln63_5_fu_458_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln63_2_fu_444_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln1_fu_468_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln2_fu_480_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln67_fu_488_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln62_fu_428_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln67_fu_492_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln67_fu_498_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln68_fu_476_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln63_1_fu_514_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln63_4_fu_528_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln63_6_fu_531_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln64_fu_521_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln63_1_fu_511_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln64_fu_540_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln64_2_fu_546_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln63_fu_534_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln63_3_fu_525_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln68_fu_556_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln68_1_fu_561_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln68_1_fu_565_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln63_fu_508_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_329_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_V_fu_584_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_332_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_V_1_fu_592_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_s_fu_600_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_1_fu_612_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_V_2_fu_624_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_12_fu_645_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal mantissa_fu_649_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_11_fu_635_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln510_fu_663_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln510_fu_667_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln1311_fu_681_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal isNeg_fu_673_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1311_fu_687_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ush_fu_691_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_prom_i_i_i_i_i_cast_cast_cast_fu_699_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_659_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal r_V_fu_707_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_9_fu_719_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_1_fu_713_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln662_fu_727_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_731_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln38_1_fu_749_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_755_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_771_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_fu_765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp13_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp68_mid1_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp685_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln36_1_fu_787_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_V_2_fu_825_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_fu_830_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_836_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln71_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln301_fu_852_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln60_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outval_V_fu_856_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln36_2_fu_806_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_325_ce : STD_LOGIC;
    signal grp_fu_329_ce : STD_LOGIC;
    signal grp_fu_332_ce : STD_LOGIC;
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal regslice_both_out_pix_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal regslice_both_in_pix_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_pix_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_TVALID_int_regslice : STD_LOGIC;
    signal in_pix_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_pix_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_pix_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_pix_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_pix_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_pix_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_pix_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_pix_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_pix_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_pix_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_pix_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_pix_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_pix_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_pix_V_last_V_U_ack_in : STD_LOGIC;
    signal out_pix_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal out_pix_TVALID_int_regslice : STD_LOGIC;
    signal out_pix_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_pix_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_pix_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_pix_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_pix_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_pix_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_pix_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_pix_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_pix_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_pix_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_pix_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_pix_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_hw_stream_dadd_64ns_64ns_64_7_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sobel_hw_stream_sitodp_32s_64_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sobel_hw_stream_line1_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_hw_stream_line2_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_hw_stream_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component sobel_hw_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    line1_V_U : component sobel_hw_stream_line1_V
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line1_V_address0,
        ce0 => line1_V_ce0,
        we0 => line1_V_we0,
        d0 => line1_V_d0,
        q0 => line1_V_q0);

    line2_V_U : component sobel_hw_stream_line2_V
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line2_V_address0,
        ce0 => line2_V_ce0,
        we0 => line2_V_we0,
        d0 => line2_V_d0,
        address1 => line2_V_address1,
        ce1 => line2_V_ce1,
        q1 => line2_V_q1);

    CTRL_s_axi_U : component sobel_hw_stream_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    dadd_64ns_64ns_64_7_full_dsp_1_U1 : component sobel_hw_stream_dadd_64ns_64ns_64_7_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_325_p0,
        din1 => grp_fu_325_p1,
        ce => grp_fu_325_ce,
        dout => grp_fu_325_p2);

    sitodp_32s_64_6_no_dsp_1_U2 : component sobel_hw_stream_sitodp_32s_64_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_329_p0,
        ce => grp_fu_329_ce,
        dout => grp_fu_329_p1);

    sitodp_32s_64_6_no_dsp_1_U3 : component sobel_hw_stream_sitodp_32s_64_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_332_p0,
        ce => grp_fu_332_ce,
        dout => grp_fu_332_p1);

    regslice_both_in_pix_V_data_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_pix_TDATA,
        vld_in => in_pix_TVALID,
        ack_in => regslice_both_in_pix_V_data_V_U_ack_in,
        data_out => in_pix_TDATA_int_regslice,
        vld_out => in_pix_TVALID_int_regslice,
        ack_out => in_pix_TREADY_int_regslice,
        apdone_blk => regslice_both_in_pix_V_data_V_U_apdone_blk);

    regslice_both_in_pix_V_keep_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_pix_TKEEP,
        vld_in => in_pix_TVALID,
        ack_in => regslice_both_in_pix_V_keep_V_U_ack_in,
        data_out => in_pix_TKEEP_int_regslice,
        vld_out => regslice_both_in_pix_V_keep_V_U_vld_out,
        ack_out => in_pix_TREADY_int_regslice,
        apdone_blk => regslice_both_in_pix_V_keep_V_U_apdone_blk);

    regslice_both_in_pix_V_strb_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_pix_TSTRB,
        vld_in => in_pix_TVALID,
        ack_in => regslice_both_in_pix_V_strb_V_U_ack_in,
        data_out => in_pix_TSTRB_int_regslice,
        vld_out => regslice_both_in_pix_V_strb_V_U_vld_out,
        ack_out => in_pix_TREADY_int_regslice,
        apdone_blk => regslice_both_in_pix_V_strb_V_U_apdone_blk);

    regslice_both_in_pix_V_last_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_pix_TLAST,
        vld_in => in_pix_TVALID,
        ack_in => regslice_both_in_pix_V_last_V_U_ack_in,
        data_out => in_pix_TLAST_int_regslice,
        vld_out => regslice_both_in_pix_V_last_V_U_vld_out,
        ack_out => in_pix_TREADY_int_regslice,
        apdone_blk => regslice_both_in_pix_V_last_V_U_apdone_blk);

    regslice_both_out_pix_V_data_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_pix_TDATA_int_regslice,
        vld_in => out_pix_TVALID_int_regslice,
        ack_in => out_pix_TREADY_int_regslice,
        data_out => out_pix_TDATA,
        vld_out => regslice_both_out_pix_V_data_V_U_vld_out,
        ack_out => out_pix_TREADY,
        apdone_blk => regslice_both_out_pix_V_data_V_U_apdone_blk);

    regslice_both_out_pix_V_keep_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_1,
        vld_in => out_pix_TVALID_int_regslice,
        ack_in => regslice_both_out_pix_V_keep_V_U_ack_in_dummy,
        data_out => out_pix_TKEEP,
        vld_out => regslice_both_out_pix_V_keep_V_U_vld_out,
        ack_out => out_pix_TREADY,
        apdone_blk => regslice_both_out_pix_V_keep_V_U_apdone_blk);

    regslice_both_out_pix_V_strb_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_1,
        vld_in => out_pix_TVALID_int_regslice,
        ack_in => regslice_both_out_pix_V_strb_V_U_ack_in_dummy,
        data_out => out_pix_TSTRB,
        vld_out => regslice_both_out_pix_V_strb_V_U_vld_out,
        ack_out => out_pix_TREADY,
        apdone_blk => regslice_both_out_pix_V_strb_V_U_apdone_blk);

    regslice_both_out_pix_V_last_V_U : component sobel_hw_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_pix_TLAST_int_regslice,
        vld_in => out_pix_TVALID_int_regslice,
        ack_in => regslice_both_out_pix_V_last_V_U_ack_in_dummy,
        data_out => out_pix_TLAST,
        vld_out => regslice_both_out_pix_V_last_V_U_vld_out,
        ack_out => out_pix_TREADY,
        apdone_blk => regslice_both_out_pix_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp1_flush_enable)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter11 <= ap_enable_reg_pp1_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter12 <= ap_enable_reg_pp1_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter13 <= ap_enable_reg_pp1_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter14 <= ap_enable_reg_pp1_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter15 <= ap_enable_reg_pp1_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter16 <= ap_enable_reg_pp1_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter17 <= ap_enable_reg_pp1_iter16;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter16 = ap_const_logic_0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter17_state21)))) then 
                    ap_enable_reg_pp1_iter17 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter18 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter17_state21))) then 
                    ap_enable_reg_pp1_iter18 <= ap_enable_reg_pp1_iter16;
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter18 <= ap_enable_reg_pp1_iter17;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp1_iter18 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp1_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_reg_209_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (init_done_load_load_fu_335_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1))) then 
                i_reg_209 <= ap_const_lv9_0;
            elsif (((icmp_ln26_fu_345_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_reg_209 <= add_ln26_fu_339_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                indvar_flatten_reg_220 <= add_ln38_fu_363_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                indvar_flatten_reg_220 <= ap_const_lv17_0;
            end if; 
        end if;
    end process;

    w01_V_1_reg_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
                w01_V_1_reg_254 <= w01_V_reg_265;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                w01_V_1_reg_254 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w01_V_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
                w01_V_reg_265 <= w02_V_reg_946;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                w01_V_reg_265 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w11_V_1_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
                w11_V_1_reg_278 <= w11_V_reg_289;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                w11_V_1_reg_278 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w11_V_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
                w11_V_reg_289 <= w12_V_reg_940;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                w11_V_reg_289 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w21_V_2_reg_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
                w21_V_2_reg_302 <= w21_V_reg_242;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                w21_V_2_reg_302 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w21_V_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
                w21_V_reg_242 <= w22_V_reg_907_pp1_iter1_reg;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                w21_V_reg_242 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    x_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                x_reg_231 <= add_ln39_fu_422_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                x_reg_231 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    y_reg_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                y_reg_314 <= select_ln38_fu_813_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                y_reg_314 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_reg_896 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                add_ln63_reg_958 <= add_ln63_fu_462_p2;
                sub_ln67_1_reg_963 <= sub_ln67_1_fu_502_p2;
                    zext_ln64_1_reg_953(7 downto 0) <= zext_ln64_1_fu_448_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln38_reg_896_pp1_iter14_reg = ap_const_lv1_0))) then
                dc_2_reg_1008 <= grp_fu_325_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then
                gx_reg_968 <= gx_fu_550_p2;
                gy_reg_973 <= gy_fu_570_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln38_reg_896 <= icmp_ln38_fu_369_p2;
                icmp_ln38_reg_896_pp1_iter1_reg <= icmp_ln38_reg_896;
                icmp_ln39_reg_900_pp1_iter1_reg <= icmp_ln39_reg_900;
                icmp_ln60_reg_925_pp1_iter1_reg <= icmp_ln60_reg_925;
                icmp_ln84_reg_930_pp1_iter1_reg <= icmp_ln84_reg_930;
                w22_V_reg_907_pp1_iter1_reg <= w22_V_reg_907;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp1_stage0_11001)) then
                icmp_ln38_reg_896_pp1_iter10_reg <= icmp_ln38_reg_896_pp1_iter9_reg;
                icmp_ln38_reg_896_pp1_iter11_reg <= icmp_ln38_reg_896_pp1_iter10_reg;
                icmp_ln38_reg_896_pp1_iter12_reg <= icmp_ln38_reg_896_pp1_iter11_reg;
                icmp_ln38_reg_896_pp1_iter13_reg <= icmp_ln38_reg_896_pp1_iter12_reg;
                icmp_ln38_reg_896_pp1_iter14_reg <= icmp_ln38_reg_896_pp1_iter13_reg;
                icmp_ln38_reg_896_pp1_iter15_reg <= icmp_ln38_reg_896_pp1_iter14_reg;
                icmp_ln38_reg_896_pp1_iter16_reg <= icmp_ln38_reg_896_pp1_iter15_reg;
                icmp_ln38_reg_896_pp1_iter17_reg <= icmp_ln38_reg_896_pp1_iter16_reg;
                icmp_ln38_reg_896_pp1_iter2_reg <= icmp_ln38_reg_896_pp1_iter1_reg;
                icmp_ln38_reg_896_pp1_iter3_reg <= icmp_ln38_reg_896_pp1_iter2_reg;
                icmp_ln38_reg_896_pp1_iter4_reg <= icmp_ln38_reg_896_pp1_iter3_reg;
                icmp_ln38_reg_896_pp1_iter5_reg <= icmp_ln38_reg_896_pp1_iter4_reg;
                icmp_ln38_reg_896_pp1_iter6_reg <= icmp_ln38_reg_896_pp1_iter5_reg;
                icmp_ln38_reg_896_pp1_iter7_reg <= icmp_ln38_reg_896_pp1_iter6_reg;
                icmp_ln38_reg_896_pp1_iter8_reg <= icmp_ln38_reg_896_pp1_iter7_reg;
                icmp_ln38_reg_896_pp1_iter9_reg <= icmp_ln38_reg_896_pp1_iter8_reg;
                icmp_ln39_reg_900_pp1_iter10_reg <= icmp_ln39_reg_900_pp1_iter9_reg;
                icmp_ln39_reg_900_pp1_iter11_reg <= icmp_ln39_reg_900_pp1_iter10_reg;
                icmp_ln39_reg_900_pp1_iter12_reg <= icmp_ln39_reg_900_pp1_iter11_reg;
                icmp_ln39_reg_900_pp1_iter13_reg <= icmp_ln39_reg_900_pp1_iter12_reg;
                icmp_ln39_reg_900_pp1_iter14_reg <= icmp_ln39_reg_900_pp1_iter13_reg;
                icmp_ln39_reg_900_pp1_iter15_reg <= icmp_ln39_reg_900_pp1_iter14_reg;
                icmp_ln39_reg_900_pp1_iter16_reg <= icmp_ln39_reg_900_pp1_iter15_reg;
                icmp_ln39_reg_900_pp1_iter2_reg <= icmp_ln39_reg_900_pp1_iter1_reg;
                icmp_ln39_reg_900_pp1_iter3_reg <= icmp_ln39_reg_900_pp1_iter2_reg;
                icmp_ln39_reg_900_pp1_iter4_reg <= icmp_ln39_reg_900_pp1_iter3_reg;
                icmp_ln39_reg_900_pp1_iter5_reg <= icmp_ln39_reg_900_pp1_iter4_reg;
                icmp_ln39_reg_900_pp1_iter6_reg <= icmp_ln39_reg_900_pp1_iter5_reg;
                icmp_ln39_reg_900_pp1_iter7_reg <= icmp_ln39_reg_900_pp1_iter6_reg;
                icmp_ln39_reg_900_pp1_iter8_reg <= icmp_ln39_reg_900_pp1_iter7_reg;
                icmp_ln39_reg_900_pp1_iter9_reg <= icmp_ln39_reg_900_pp1_iter8_reg;
                icmp_ln60_reg_925_pp1_iter10_reg <= icmp_ln60_reg_925_pp1_iter9_reg;
                icmp_ln60_reg_925_pp1_iter11_reg <= icmp_ln60_reg_925_pp1_iter10_reg;
                icmp_ln60_reg_925_pp1_iter12_reg <= icmp_ln60_reg_925_pp1_iter11_reg;
                icmp_ln60_reg_925_pp1_iter13_reg <= icmp_ln60_reg_925_pp1_iter12_reg;
                icmp_ln60_reg_925_pp1_iter14_reg <= icmp_ln60_reg_925_pp1_iter13_reg;
                icmp_ln60_reg_925_pp1_iter15_reg <= icmp_ln60_reg_925_pp1_iter14_reg;
                icmp_ln60_reg_925_pp1_iter16_reg <= icmp_ln60_reg_925_pp1_iter15_reg;
                icmp_ln60_reg_925_pp1_iter2_reg <= icmp_ln60_reg_925_pp1_iter1_reg;
                icmp_ln60_reg_925_pp1_iter3_reg <= icmp_ln60_reg_925_pp1_iter2_reg;
                icmp_ln60_reg_925_pp1_iter4_reg <= icmp_ln60_reg_925_pp1_iter3_reg;
                icmp_ln60_reg_925_pp1_iter5_reg <= icmp_ln60_reg_925_pp1_iter4_reg;
                icmp_ln60_reg_925_pp1_iter6_reg <= icmp_ln60_reg_925_pp1_iter5_reg;
                icmp_ln60_reg_925_pp1_iter7_reg <= icmp_ln60_reg_925_pp1_iter6_reg;
                icmp_ln60_reg_925_pp1_iter8_reg <= icmp_ln60_reg_925_pp1_iter7_reg;
                icmp_ln60_reg_925_pp1_iter9_reg <= icmp_ln60_reg_925_pp1_iter8_reg;
                icmp_ln84_reg_930_pp1_iter10_reg <= icmp_ln84_reg_930_pp1_iter9_reg;
                icmp_ln84_reg_930_pp1_iter11_reg <= icmp_ln84_reg_930_pp1_iter10_reg;
                icmp_ln84_reg_930_pp1_iter12_reg <= icmp_ln84_reg_930_pp1_iter11_reg;
                icmp_ln84_reg_930_pp1_iter13_reg <= icmp_ln84_reg_930_pp1_iter12_reg;
                icmp_ln84_reg_930_pp1_iter14_reg <= icmp_ln84_reg_930_pp1_iter13_reg;
                icmp_ln84_reg_930_pp1_iter15_reg <= icmp_ln84_reg_930_pp1_iter14_reg;
                icmp_ln84_reg_930_pp1_iter16_reg <= icmp_ln84_reg_930_pp1_iter15_reg;
                icmp_ln84_reg_930_pp1_iter2_reg <= icmp_ln84_reg_930_pp1_iter1_reg;
                icmp_ln84_reg_930_pp1_iter3_reg <= icmp_ln84_reg_930_pp1_iter2_reg;
                icmp_ln84_reg_930_pp1_iter4_reg <= icmp_ln84_reg_930_pp1_iter3_reg;
                icmp_ln84_reg_930_pp1_iter5_reg <= icmp_ln84_reg_930_pp1_iter4_reg;
                icmp_ln84_reg_930_pp1_iter6_reg <= icmp_ln84_reg_930_pp1_iter5_reg;
                icmp_ln84_reg_930_pp1_iter7_reg <= icmp_ln84_reg_930_pp1_iter6_reg;
                icmp_ln84_reg_930_pp1_iter8_reg <= icmp_ln84_reg_930_pp1_iter7_reg;
                icmp_ln84_reg_930_pp1_iter9_reg <= icmp_ln84_reg_930_pp1_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln39_reg_900 <= icmp_ln39_fu_375_p2;
                icmp_ln60_reg_925 <= icmp_ln60_fu_410_p2;
                icmp_ln84_reg_930 <= icmp_ln84_fu_416_p2;
                line2_V_addr_1_reg_919 <= zext_ln39_fu_389_p1(8 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (init_done_load_reg_879 = ap_const_lv1_0))) then
                init_done <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                init_done_load_reg_879 <= init_done;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln38_reg_896_pp1_iter15_reg = ap_const_lv1_0))) then
                p_Result_2_reg_1013 <= data_V_2_fu_624_p1(63 downto 63);
                val_reg_1018 <= val_fu_741_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln38_reg_896_pp1_iter7_reg = ap_const_lv1_0))) then
                trunc_ln368_1_reg_993 <= trunc_ln368_1_fu_596_p1;
                trunc_ln368_reg_988 <= trunc_ln368_fu_588_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_reg_896 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                w02_V_reg_946 <= line2_V_q1;
                w12_V_reg_940 <= line1_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                w22_V_reg_907 <= in_pix_TDATA_int_regslice;
            end if;
        end if;
    end process;
    zext_ln64_1_reg_953(8) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp1_iter17, init_done_load_load_fu_335_p1, ap_CS_fsm_state2, ap_block_pp1_stage0_subdone, ap_enable_reg_pp1_iter16, icmp_ln26_fu_345_p2, ap_CS_fsm_state23, regslice_both_out_pix_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (init_done_load_load_fu_335_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (init_done_load_load_fu_335_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln26_fu_345_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_enable_reg_pp1_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter16 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_enable_reg_pp1_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter16 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state23 => 
                if (((regslice_both_out_pix_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state23))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state23;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln26_fu_339_p2 <= std_logic_vector(unsigned(i_reg_209) + unsigned(ap_const_lv9_1));
    add_ln38_1_fu_749_p2 <= std_logic_vector(unsigned(y_reg_314) + unsigned(ap_const_lv9_1));
    add_ln38_fu_363_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_220) + unsigned(ap_const_lv17_1));
    add_ln39_fu_422_p2 <= std_logic_vector(unsigned(select_ln36_fu_381_p3) + unsigned(ap_const_lv9_1));
    add_ln510_fu_667_p2 <= std_logic_vector(unsigned(zext_ln510_fu_663_p1) + unsigned(ap_const_lv12_C01));
    add_ln63_1_fu_452_p2 <= std_logic_vector(unsigned(zext_ln62_1_fu_432_p1) + unsigned(zext_ln64_1_fu_448_p1));
    add_ln63_fu_462_p2 <= std_logic_vector(unsigned(zext_ln63_5_fu_458_p1) + unsigned(zext_ln63_2_fu_444_p1));
    add_ln64_fu_540_p2 <= std_logic_vector(unsigned(zext_ln64_fu_521_p1) + unsigned(zext_ln63_1_fu_511_p1));
    add_ln68_1_fu_565_p2 <= std_logic_vector(unsigned(zext_ln68_1_fu_561_p1) + unsigned(sub_ln67_1_reg_963));
    add_ln68_fu_556_p2 <= std_logic_vector(unsigned(zext_ln64_1_reg_953) + unsigned(zext_ln63_3_fu_525_p1));
    and_ln60_fu_820_p2 <= (select_ln36_1_fu_787_p3 and icmp_ln60_reg_925_pp1_iter16_reg);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state23 <= ap_CS_fsm(4);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(ap_enable_reg_pp1_iter0, icmp_ln38_fu_369_p2, ap_enable_reg_pp1_iter17, icmp_ln38_reg_896_pp1_iter16_reg, ap_enable_reg_pp1_iter18, icmp_ln38_reg_896_pp1_iter17_reg, in_pix_TVALID_int_regslice, out_pix_TREADY_int_regslice)
    begin
                ap_block_pp1_stage0_01001 <= (((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter17_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter18 = ap_const_logic_1)) or ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter17 = ap_const_logic_1)) or ((in_pix_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(ap_enable_reg_pp1_iter0, icmp_ln38_fu_369_p2, ap_enable_reg_pp1_iter17, icmp_ln38_reg_896_pp1_iter16_reg, ap_enable_reg_pp1_iter18, icmp_ln38_reg_896_pp1_iter17_reg, ap_block_state21_io, ap_block_state22_io, in_pix_TVALID_int_regslice, out_pix_TREADY_int_regslice)
    begin
                ap_block_pp1_stage0_11001 <= (((in_pix_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp1_iter18 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state22_io) or ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter17_reg = ap_const_lv1_0)))) or ((ap_enable_reg_pp1_iter17 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state21_io) or ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0)))));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(ap_enable_reg_pp1_iter0, icmp_ln38_fu_369_p2, ap_enable_reg_pp1_iter17, icmp_ln38_reg_896_pp1_iter16_reg, ap_enable_reg_pp1_iter18, icmp_ln38_reg_896_pp1_iter17_reg, ap_block_state21_io, ap_block_state22_io, in_pix_TVALID_int_regslice, out_pix_TREADY_int_regslice)
    begin
                ap_block_pp1_stage0_subdone <= (((in_pix_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp1_iter18 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state22_io) or ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter17_reg = ap_const_lv1_0)))) or ((ap_enable_reg_pp1_iter17 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state21_io) or ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0)))));
    end process;

        ap_block_state10_pp1_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp1_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp1_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp1_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp1_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp1_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp1_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp1_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp1_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp1_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp1_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state21_io_assign_proc : process(icmp_ln38_reg_896_pp1_iter16_reg, out_pix_TREADY_int_regslice)
    begin
                ap_block_state21_io <= ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0));
    end process;


    ap_block_state21_pp1_stage0_iter17_assign_proc : process(icmp_ln38_reg_896_pp1_iter16_reg, out_pix_TREADY_int_regslice)
    begin
                ap_block_state21_pp1_stage0_iter17 <= ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0));
    end process;


    ap_block_state22_io_assign_proc : process(icmp_ln38_reg_896_pp1_iter17_reg, out_pix_TREADY_int_regslice)
    begin
                ap_block_state22_io <= ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter17_reg = ap_const_lv1_0));
    end process;


    ap_block_state22_pp1_stage0_iter18_assign_proc : process(icmp_ln38_reg_896_pp1_iter17_reg, out_pix_TREADY_int_regslice)
    begin
                ap_block_state22_pp1_stage0_iter18 <= ((out_pix_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln38_reg_896_pp1_iter17_reg = ap_const_lv1_0));
    end process;


    ap_block_state4_pp1_stage0_iter0_assign_proc : process(icmp_ln38_fu_369_p2, in_pix_TVALID_int_regslice)
    begin
                ap_block_state4_pp1_stage0_iter0 <= ((in_pix_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln38_fu_369_p2 = ap_const_lv1_0));
    end process;

        ap_block_state5_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp1_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp1_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp1_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp1_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp1_exit_iter17_state21_assign_proc : process(ap_enable_reg_pp1_iter17, ap_enable_reg_pp1_iter16)
    begin
        if (((ap_enable_reg_pp1_iter17 = ap_const_logic_1) and (ap_enable_reg_pp1_iter16 = ap_const_logic_0))) then 
            ap_condition_pp1_exit_iter17_state21 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter17_state21 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_flush_enable_assign_proc : process(ap_CS_fsm_pp1_stage0, icmp_ln38_fu_369_p2, ap_block_pp1_stage0_subdone)
    begin
        if (((icmp_ln38_fu_369_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_condition_pp1_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp1_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state23, regslice_both_out_pix_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_pix_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter17, ap_enable_reg_pp1_iter18, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter2, ap_enable_reg_pp1_iter3, ap_enable_reg_pp1_iter4, ap_enable_reg_pp1_iter5, ap_enable_reg_pp1_iter6, ap_enable_reg_pp1_iter7, ap_enable_reg_pp1_iter8, ap_enable_reg_pp1_iter9, ap_enable_reg_pp1_iter10, ap_enable_reg_pp1_iter11, ap_enable_reg_pp1_iter12, ap_enable_reg_pp1_iter13, ap_enable_reg_pp1_iter14, ap_enable_reg_pp1_iter15, ap_enable_reg_pp1_iter16)
    begin
        if (((ap_enable_reg_pp1_iter18 = ap_const_logic_0) and (ap_enable_reg_pp1_iter17 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_enable_reg_pp1_iter16 = ap_const_logic_0) and (ap_enable_reg_pp1_iter15 = ap_const_logic_0) and (ap_enable_reg_pp1_iter14 = ap_const_logic_0) and (ap_enable_reg_pp1_iter13 = ap_const_logic_0) and (ap_enable_reg_pp1_iter12 = ap_const_logic_0) and (ap_enable_reg_pp1_iter11 = ap_const_logic_0) and (ap_enable_reg_pp1_iter10 = ap_const_logic_0) and (ap_enable_reg_pp1_iter9 = ap_const_logic_0) and (ap_enable_reg_pp1_iter8 = ap_const_logic_0) and (ap_enable_reg_pp1_iter7 = ap_const_logic_0) and (ap_enable_reg_pp1_iter6 = ap_const_logic_0) and (ap_enable_reg_pp1_iter5 = ap_const_logic_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_w01_V_1_phi_fu_258_p4_assign_proc : process(ap_block_pp1_stage0, w01_V_1_reg_254, w01_V_reg_265, icmp_ln38_reg_896_pp1_iter1_reg, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_w01_V_1_phi_fu_258_p4 <= w01_V_reg_265;
        else 
            ap_phi_mux_w01_V_1_phi_fu_258_p4 <= w01_V_1_reg_254;
        end if; 
    end process;


    ap_phi_mux_w01_V_phi_fu_270_p4_assign_proc : process(ap_block_pp1_stage0, w01_V_reg_265, icmp_ln38_reg_896_pp1_iter1_reg, w02_V_reg_946, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_w01_V_phi_fu_270_p4 <= w02_V_reg_946;
        else 
            ap_phi_mux_w01_V_phi_fu_270_p4 <= w01_V_reg_265;
        end if; 
    end process;


    ap_phi_mux_w11_V_1_phi_fu_282_p4_assign_proc : process(ap_block_pp1_stage0, w11_V_1_reg_278, w11_V_reg_289, icmp_ln38_reg_896_pp1_iter1_reg, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_w11_V_1_phi_fu_282_p4 <= w11_V_reg_289;
        else 
            ap_phi_mux_w11_V_1_phi_fu_282_p4 <= w11_V_1_reg_278;
        end if; 
    end process;


    ap_phi_mux_w21_V_2_phi_fu_306_p4_assign_proc : process(ap_block_pp1_stage0, w21_V_reg_242, w21_V_2_reg_302, icmp_ln38_reg_896_pp1_iter1_reg, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_w21_V_2_phi_fu_306_p4 <= w21_V_reg_242;
        else 
            ap_phi_mux_w21_V_2_phi_fu_306_p4 <= w21_V_2_reg_302;
        end if; 
    end process;


    ap_phi_mux_w21_V_phi_fu_246_p4_assign_proc : process(ap_block_pp1_stage0, w21_V_reg_242, icmp_ln38_reg_896_pp1_iter1_reg, w22_V_reg_907_pp1_iter1_reg, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (icmp_ln38_reg_896_pp1_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_w21_V_phi_fu_246_p4 <= w22_V_reg_907_pp1_iter1_reg;
        else 
            ap_phi_mux_w21_V_phi_fu_246_p4 <= w21_V_reg_242;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state23, regslice_both_out_pix_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_pix_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    cmp685_fu_800_p2 <= "1" when (y_reg_314 = ap_const_lv9_FF) else "0";
    cmp68_mid1_fu_794_p2 <= "1" when (add_ln38_1_fu_749_p2 = ap_const_lv9_FF) else "0";
    data_V_1_fu_592_p1 <= grp_fu_332_p1;
    data_V_2_fu_624_p1 <= dc_2_reg_1008;
    data_V_fu_584_p1 <= grp_fu_329_p1;

    grp_fu_325_ce_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            grp_fu_325_ce <= ap_const_logic_1;
        else 
            grp_fu_325_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_325_p0 <= p_Result_s_fu_600_p3;
    grp_fu_325_p1 <= p_Result_1_fu_612_p3;

    grp_fu_329_ce_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            grp_fu_329_ce <= ap_const_logic_1;
        else 
            grp_fu_329_ce <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_329_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(gx_reg_968),32));


    grp_fu_332_ce_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            grp_fu_332_ce <= ap_const_logic_1;
        else 
            grp_fu_332_ce <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_332_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(gy_reg_973),32));

    gx_fu_550_p2 <= std_logic_vector(unsigned(zext_ln64_2_fu_546_p1) + unsigned(sub_ln63_fu_534_p2));
    gy_fu_570_p2 <= std_logic_vector(unsigned(add_ln68_1_fu_565_p2) - unsigned(zext_ln63_fu_508_p1));
    icmp13_fu_781_p2 <= "0" when (tmp_1_fu_771_p4 = ap_const_lv8_0) else "1";
    icmp_fu_765_p2 <= "0" when (tmp_fu_755_p4 = ap_const_lv8_0) else "1";
    icmp_ln26_fu_345_p2 <= "1" when (i_reg_209 = ap_const_lv9_100) else "0";
    icmp_ln38_fu_369_p2 <= "1" when (indvar_flatten_reg_220 = ap_const_lv17_10000) else "0";
    icmp_ln39_fu_375_p2 <= "1" when (x_reg_231 = ap_const_lv9_100) else "0";
    icmp_ln60_fu_410_p2 <= "0" when (tmp_2_fu_400_p4 = ap_const_lv8_0) else "1";
    icmp_ln71_fu_846_p2 <= "1" when (signed(tmp_10_fu_836_p4) > signed(ap_const_lv24_0)) else "0";
    icmp_ln84_fu_416_p2 <= "1" when (select_ln36_fu_381_p3 = ap_const_lv9_FF) else "0";

    in_pix_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0, icmp_ln38_fu_369_p2, in_pix_TVALID_int_regslice)
    begin
        if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            in_pix_TDATA_blk_n <= in_pix_TVALID_int_regslice;
        else 
            in_pix_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_pix_TREADY <= regslice_both_in_pix_V_data_V_U_ack_in;

    in_pix_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, icmp_ln38_fu_369_p2, ap_block_pp1_stage0_11001)
    begin
        if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            in_pix_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_pix_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    init_done_load_load_fu_335_p1 <= init_done;
    isNeg_fu_673_p3 <= add_ln510_fu_667_p2(11 downto 11);

    line1_V_address0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0, icmp_ln38_fu_369_p2, ap_CS_fsm_state2, zext_ln26_fu_351_p1, zext_ln39_fu_389_p1)
    begin
        if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            line1_V_address0 <= zext_ln39_fu_389_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line1_V_address0 <= zext_ln26_fu_351_p1(8 - 1 downto 0);
        else 
            line1_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    line1_V_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, icmp_ln38_fu_369_p2, ap_CS_fsm_state2, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            line1_V_ce0 <= ap_const_logic_1;
        else 
            line1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line1_V_d0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0, icmp_ln38_fu_369_p2, ap_CS_fsm_state2, in_pix_TDATA_int_regslice)
    begin
        if (((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            line1_V_d0 <= in_pix_TDATA_int_regslice;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line1_V_d0 <= ap_const_lv8_0;
        else 
            line1_V_d0 <= "XXXXXXXX";
        end if; 
    end process;


    line1_V_we0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, icmp_ln38_fu_369_p2, ap_CS_fsm_state2, ap_block_pp1_stage0_11001, icmp_ln26_fu_345_p2)
    begin
        if ((((icmp_ln38_fu_369_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((icmp_ln26_fu_345_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            line1_V_we0 <= ap_const_logic_1;
        else 
            line1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line2_V_address0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_CS_fsm_state2, line2_V_addr_1_reg_919, ap_enable_reg_pp1_iter1, zext_ln26_fu_351_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            line2_V_address0 <= line2_V_addr_1_reg_919;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line2_V_address0 <= zext_ln26_fu_351_p1(8 - 1 downto 0);
        else 
            line2_V_address0 <= "XXXXXXXX";
        end if; 
    end process;

    line2_V_address1 <= zext_ln39_fu_389_p1(8 - 1 downto 0);

    line2_V_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_CS_fsm_state2, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            line2_V_ce0 <= ap_const_logic_1;
        else 
            line2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line2_V_ce1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            line2_V_ce1 <= ap_const_logic_1;
        else 
            line2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line2_V_d0_assign_proc : process(line1_V_q0, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_CS_fsm_state2, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            line2_V_d0 <= line1_V_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line2_V_d0 <= ap_const_lv8_0;
        else 
            line2_V_d0 <= "XXXXXXXX";
        end if; 
    end process;


    line2_V_we0_assign_proc : process(ap_CS_fsm_pp1_stage0, icmp_ln38_reg_896, ap_CS_fsm_state2, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter1, icmp_ln26_fu_345_p2)
    begin
        if ((((icmp_ln26_fu_345_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln38_reg_896 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            line2_V_we0 <= ap_const_logic_1;
        else 
            line2_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    mantissa_fu_649_p4 <= ((ap_const_lv1_1 & tmp_12_fu_645_p1) & ap_const_lv1_0);

    out_pix_TDATA_blk_n_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter17, icmp_ln38_reg_896_pp1_iter16_reg, ap_enable_reg_pp1_iter18, icmp_ln38_reg_896_pp1_iter17_reg, out_pix_TREADY_int_regslice)
    begin
        if ((((icmp_ln38_reg_896_pp1_iter17_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter18 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0)) or ((icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0)))) then 
            out_pix_TDATA_blk_n <= out_pix_TREADY_int_regslice;
        else 
            out_pix_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_pix_TDATA_int_regslice <= 
        outval_V_fu_856_p3 when (and_ln60_fu_820_p2(0) = '1') else 
        ap_const_lv8_0;
    out_pix_TLAST_int_regslice <= (select_ln36_2_fu_806_p3 and icmp_ln84_reg_930_pp1_iter16_reg);
    out_pix_TVALID <= regslice_both_out_pix_V_data_V_U_vld_out;

    out_pix_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp1_iter17, icmp_ln38_reg_896_pp1_iter16_reg, ap_block_pp1_stage0_11001)
    begin
        if (((icmp_ln38_reg_896_pp1_iter16_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            out_pix_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_pix_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    outval_V_fu_856_p3 <= 
        ap_const_lv8_FF when (icmp_ln71_fu_846_p2(0) = '1') else 
        trunc_ln301_fu_852_p1;
    p_Result_1_fu_612_p3 <= (ap_const_lv1_0 & trunc_ln368_1_reg_993);
    p_Result_s_fu_600_p3 <= (ap_const_lv1_0 & trunc_ln368_reg_988);
    r_V_1_fu_713_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_659_p1),to_integer(unsigned('0' & sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1(31-1 downto 0)))));
    r_V_fu_707_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_659_p1),to_integer(unsigned('0' & sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1(31-1 downto 0)))));
    result_V_2_fu_825_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_reg_1018));
    result_V_fu_830_p3 <= 
        result_V_2_fu_825_p2 when (p_Result_2_reg_1013(0) = '1') else 
        val_reg_1018;
    select_ln36_1_fu_787_p3 <= 
        icmp_fu_765_p2 when (icmp_ln39_reg_900_pp1_iter16_reg(0) = '1') else 
        icmp13_fu_781_p2;
    select_ln36_2_fu_806_p3 <= 
        cmp68_mid1_fu_794_p2 when (icmp_ln39_reg_900_pp1_iter16_reg(0) = '1') else 
        cmp685_fu_800_p2;
    select_ln36_fu_381_p3 <= 
        ap_const_lv9_0 when (icmp_ln39_fu_375_p2(0) = '1') else 
        x_reg_231;
    select_ln38_fu_813_p3 <= 
        add_ln38_1_fu_749_p2 when (icmp_ln39_reg_900_pp1_iter16_reg(0) = '1') else 
        y_reg_314;
        sext_ln1311_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1311_fu_681_p2),12));

        sext_ln67_fu_498_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln67_fu_492_p2),11));

    sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_703_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_prom_i_i_i_i_i_cast_cast_cast_fu_699_p1),137));
        sh_prom_i_i_i_i_i_cast_cast_cast_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_fu_691_p3),32));

    shl_ln1_fu_468_p3 <= (ap_phi_mux_w01_V_phi_fu_270_p4 & ap_const_lv1_0);
    shl_ln2_fu_480_p3 <= (ap_phi_mux_w21_V_phi_fu_246_p4 & ap_const_lv1_0);
    shl_ln63_1_fu_514_p3 <= (w12_V_reg_940 & ap_const_lv1_0);
    shl_ln_fu_436_p3 <= (ap_phi_mux_w11_V_1_phi_fu_282_p4 & ap_const_lv1_0);
    sub_ln1311_fu_681_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(tmp_11_fu_635_p4));
    sub_ln63_fu_534_p2 <= std_logic_vector(unsigned(zext_ln63_4_fu_528_p1) - unsigned(zext_ln63_6_fu_531_p1));
    sub_ln67_1_fu_502_p2 <= std_logic_vector(signed(sext_ln67_fu_498_p1) - signed(zext_ln68_fu_476_p1));
    sub_ln67_fu_492_p2 <= std_logic_vector(unsigned(zext_ln67_fu_488_p1) - unsigned(zext_ln62_fu_428_p1));
    tmp_10_fu_836_p4 <= result_V_fu_830_p3(31 downto 8);
    tmp_11_fu_635_p4 <= data_V_2_fu_624_p1(62 downto 52);
    tmp_12_fu_645_p1 <= data_V_2_fu_624_p1(52 - 1 downto 0);
    tmp_1_fu_771_p4 <= y_reg_314(8 downto 1);
    tmp_2_fu_400_p4 <= select_ln36_fu_381_p3(8 downto 1);
    tmp_6_fu_731_p4 <= r_V_1_fu_713_p2(84 downto 53);
    tmp_9_fu_719_p3 <= r_V_fu_707_p2(53 downto 53);
    tmp_fu_755_p4 <= add_ln38_1_fu_749_p2(8 downto 1);
    trunc_ln301_fu_852_p1 <= result_V_fu_830_p3(8 - 1 downto 0);
    trunc_ln368_1_fu_596_p1 <= data_V_1_fu_592_p1(63 - 1 downto 0);
    trunc_ln368_fu_588_p1 <= data_V_fu_584_p1(63 - 1 downto 0);
    ush_fu_691_p3 <= 
        sext_ln1311_fu_687_p1 when (isNeg_fu_673_p3(0) = '1') else 
        add_ln510_fu_667_p2;
    val_fu_741_p3 <= 
        zext_ln662_fu_727_p1 when (isNeg_fu_673_p3(0) = '1') else 
        tmp_6_fu_731_p4;
    zext_ln15_fu_659_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_649_p4),137));
    zext_ln26_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_209),64));
    zext_ln39_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln36_fu_381_p3),64));
    zext_ln510_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_635_p4),12));
    zext_ln62_1_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_w01_V_1_phi_fu_258_p4),9));
    zext_ln62_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_w01_V_1_phi_fu_258_p4),10));
    zext_ln63_1_fu_511_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w02_V_reg_946),10));
    zext_ln63_2_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_436_p3),10));
    zext_ln63_3_fu_525_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w22_V_reg_907_pp1_iter1_reg),9));
    zext_ln63_4_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w22_V_reg_907_pp1_iter1_reg),11));
    zext_ln63_5_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_1_fu_452_p2),10));
    zext_ln63_6_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_reg_958),11));
    zext_ln63_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w02_V_reg_946),11));
    zext_ln64_1_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_w21_V_2_phi_fu_306_p4),9));
    zext_ln64_2_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_fu_540_p2),11));
    zext_ln64_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln63_1_fu_514_p3),10));
    zext_ln662_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_719_p3),32));
    zext_ln67_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_480_p3),10));
    zext_ln68_1_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln68_fu_556_p2),11));
    zext_ln68_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_468_p3),11));
end behav;
